# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'perception.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10perception.proto\x12\x0eterra_perceive\"U\n\x06Header\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x16\n\x0eschema_version\x18\x03 \x01(\r\x12\x0e\n\x06source\x18\x04 \x01(\t\"\xfe\x01\n\x07\x42\x45VGrid\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.terra_perceive.Header\x12\x12\n\nresolution\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x10\n\x08origin_x\x18\x05 \x01(\x02\x12\x10\n\x08origin_y\x18\x06 \x01(\x02\x12\x0e\n\x06scores\x18\x07 \x03(\x02\x12\x12\n\nconfidence\x18\x08 \x03(\x02\x12\x19\n\x11observation_count\x18\t \x03(\r\x12\x15\n\rcoverage_mask\x18\n \x01(\x0c\x12\x1e\n\x16pose_sigma_at_snapshot\x18\x0b \x01(\x02\"\x81\x01\n\x0b\x44\x65tection2D\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x05 \x01(\x05\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12\x10\n\x08\x64\x65pth_3d\x18\x07 \x01(\x02\"h\n\rDetectionList\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.terra_perceive.Header\x12/\n\ndetections\x18\x02 \x03(\x0b\x32\x1b.terra_perceive.Detection2D\"}\n\rTrackedObject\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\n\n\x02vx\x18\x05 \x01(\x02\x12\n\n\x02vy\x18\x06 \x01(\x02\x12\x0c\n\x04z_3d\x18\x07 \x01(\x02\x12\x0c\n\x04hits\x18\x08 \x01(\x05\"b\n\tTrackList\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.terra_perceive.Header\x12-\n\x06tracks\x18\x02 \x03(\x0b\x32\x1d.terra_perceive.TrackedObject\"t\n\x0b\x43\x61meraFrame\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.terra_perceive.Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=36
  _globals['_HEADER']._serialized_end=121
  _globals['_BEVGRID']._serialized_start=124
  _globals['_BEVGRID']._serialized_end=378
  _globals['_DETECTION2D']._serialized_start=381
  _globals['_DETECTION2D']._serialized_end=510
  _globals['_DETECTIONLIST']._serialized_start=512
  _globals['_DETECTIONLIST']._serialized_end=616
  _globals['_TRACKEDOBJECT']._serialized_start=618
  _globals['_TRACKEDOBJECT']._serialized_end=743
  _globals['_TRACKLIST']._serialized_start=745
  _globals['_TRACKLIST']._serialized_end=843
  _globals['_CAMERAFRAME']._serialized_start=845
  _globals['_CAMERAFRAME']._serialized_end=961
# @@protoc_insertion_point(module_scope)
