# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: safety.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'safety.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csafety.proto\x12\x0eterra_perceive\"k\n\x0cSafeVelocity\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08linear_x\x18\x02 \x01(\x02\x12\x11\n\tangular_z\x18\x03 \x01(\x02\x12\x13\n\x0b\x61\x63tive_rule\x18\x04 \x01(\t\x12\x0e\n\x06reason\x18\x05 \x01(\t\"}\n\x0bSafetyEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04rule\x18\x02 \x01(\t\x12\x15\n\rtrigger_value\x18\x03 \x01(\x02\x12\x12\n\nvel_before\x18\x04 \x01(\x02\x12\x11\n\tvel_after\x18\x05 \x01(\x02\x12\x0f\n\x07\x64\x65tails\x18\x06 \x01(\t\"=\n\x0eSafetyEventLog\x12+\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1b.terra_perceive.SafetyEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'safety_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAFEVELOCITY']._serialized_start=32
  _globals['_SAFEVELOCITY']._serialized_end=139
  _globals['_SAFETYEVENT']._serialized_start=141
  _globals['_SAFETYEVENT']._serialized_end=266
  _globals['_SAFETYEVENTLOG']._serialized_start=268
  _globals['_SAFETYEVENTLOG']._serialized_end=329
# @@protoc_insertion_point(module_scope)
