// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: safety.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_safety_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_safety_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_safety_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_safety_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_safety_2eproto;
namespace terra_perceive {
class SafeVelocity;
class SafeVelocityDefaultTypeInternal;
extern SafeVelocityDefaultTypeInternal _SafeVelocity_default_instance_;
class SafetyEvent;
class SafetyEventDefaultTypeInternal;
extern SafetyEventDefaultTypeInternal _SafetyEvent_default_instance_;
class SafetyEventLog;
class SafetyEventLogDefaultTypeInternal;
extern SafetyEventLogDefaultTypeInternal _SafetyEventLog_default_instance_;
}  // namespace terra_perceive
PROTOBUF_NAMESPACE_OPEN
template<> ::terra_perceive::SafeVelocity* Arena::CreateMaybeMessage<::terra_perceive::SafeVelocity>(Arena*);
template<> ::terra_perceive::SafetyEvent* Arena::CreateMaybeMessage<::terra_perceive::SafetyEvent>(Arena*);
template<> ::terra_perceive::SafetyEventLog* Arena::CreateMaybeMessage<::terra_perceive::SafetyEventLog>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace terra_perceive {

// ===================================================================

class SafeVelocity PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:terra_perceive.SafeVelocity) */ {
 public:
  inline SafeVelocity() : SafeVelocity(nullptr) {};
  virtual ~SafeVelocity();

  SafeVelocity(const SafeVelocity& from);
  SafeVelocity(SafeVelocity&& from) noexcept
    : SafeVelocity() {
    *this = ::std::move(from);
  }

  inline SafeVelocity& operator=(const SafeVelocity& from) {
    CopyFrom(from);
    return *this;
  }
  inline SafeVelocity& operator=(SafeVelocity&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SafeVelocity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SafeVelocity* internal_default_instance() {
    return reinterpret_cast<const SafeVelocity*>(
               &_SafeVelocity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SafeVelocity& a, SafeVelocity& b) {
    a.Swap(&b);
  }
  inline void Swap(SafeVelocity* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SafeVelocity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SafeVelocity* New() const final {
    return CreateMaybeMessage<SafeVelocity>(nullptr);
  }

  SafeVelocity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SafeVelocity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SafeVelocity& from);
  void MergeFrom(const SafeVelocity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SafeVelocity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "terra_perceive.SafeVelocity";
  }
  protected:
  explicit SafeVelocity(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_safety_2eproto);
    return ::descriptor_table_safety_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActiveRuleFieldNumber = 4,
    kReasonFieldNumber = 5,
    kTimestampFieldNumber = 1,
    kLinearXFieldNumber = 2,
    kAngularZFieldNumber = 3,
  };
  // string active_rule = 4;
  void clear_active_rule();
  const std::string& active_rule() const;
  void set_active_rule(const std::string& value);
  void set_active_rule(std::string&& value);
  void set_active_rule(const char* value);
  void set_active_rule(const char* value, size_t size);
  std::string* mutable_active_rule();
  std::string* release_active_rule();
  void set_allocated_active_rule(std::string* active_rule);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_active_rule();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_active_rule(
      std::string* active_rule);
  private:
  const std::string& _internal_active_rule() const;
  void _internal_set_active_rule(const std::string& value);
  std::string* _internal_mutable_active_rule();
  public:

  // string reason = 5;
  void clear_reason();
  const std::string& reason() const;
  void set_reason(const std::string& value);
  void set_reason(std::string&& value);
  void set_reason(const char* value);
  void set_reason(const char* value, size_t size);
  std::string* mutable_reason();
  std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_reason();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_reason(
      std::string* reason);
  private:
  const std::string& _internal_reason() const;
  void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // double timestamp = 1;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);
  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);
  public:

  // float linear_x = 2;
  void clear_linear_x();
  float linear_x() const;
  void set_linear_x(float value);
  private:
  float _internal_linear_x() const;
  void _internal_set_linear_x(float value);
  public:

  // float angular_z = 3;
  void clear_angular_z();
  float angular_z() const;
  void set_angular_z(float value);
  private:
  float _internal_angular_z() const;
  void _internal_set_angular_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:terra_perceive.SafeVelocity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr active_rule_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
  double timestamp_;
  float linear_x_;
  float angular_z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_safety_2eproto;
};
// -------------------------------------------------------------------

class SafetyEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:terra_perceive.SafetyEvent) */ {
 public:
  inline SafetyEvent() : SafetyEvent(nullptr) {};
  virtual ~SafetyEvent();

  SafetyEvent(const SafetyEvent& from);
  SafetyEvent(SafetyEvent&& from) noexcept
    : SafetyEvent() {
    *this = ::std::move(from);
  }

  inline SafetyEvent& operator=(const SafetyEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline SafetyEvent& operator=(SafetyEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SafetyEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SafetyEvent* internal_default_instance() {
    return reinterpret_cast<const SafetyEvent*>(
               &_SafetyEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SafetyEvent& a, SafetyEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(SafetyEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SafetyEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SafetyEvent* New() const final {
    return CreateMaybeMessage<SafetyEvent>(nullptr);
  }

  SafetyEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SafetyEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SafetyEvent& from);
  void MergeFrom(const SafetyEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SafetyEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "terra_perceive.SafetyEvent";
  }
  protected:
  explicit SafetyEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_safety_2eproto);
    return ::descriptor_table_safety_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuleFieldNumber = 2,
    kDetailsFieldNumber = 6,
    kTimestampFieldNumber = 1,
    kTriggerValueFieldNumber = 3,
    kVelBeforeFieldNumber = 4,
    kVelAfterFieldNumber = 5,
  };
  // string rule = 2;
  void clear_rule();
  const std::string& rule() const;
  void set_rule(const std::string& value);
  void set_rule(std::string&& value);
  void set_rule(const char* value);
  void set_rule(const char* value, size_t size);
  std::string* mutable_rule();
  std::string* release_rule();
  void set_allocated_rule(std::string* rule);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_rule();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_rule(
      std::string* rule);
  private:
  const std::string& _internal_rule() const;
  void _internal_set_rule(const std::string& value);
  std::string* _internal_mutable_rule();
  public:

  // string details = 6;
  void clear_details();
  const std::string& details() const;
  void set_details(const std::string& value);
  void set_details(std::string&& value);
  void set_details(const char* value);
  void set_details(const char* value, size_t size);
  std::string* mutable_details();
  std::string* release_details();
  void set_allocated_details(std::string* details);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_details();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_details(
      std::string* details);
  private:
  const std::string& _internal_details() const;
  void _internal_set_details(const std::string& value);
  std::string* _internal_mutable_details();
  public:

  // double timestamp = 1;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);
  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);
  public:

  // float trigger_value = 3;
  void clear_trigger_value();
  float trigger_value() const;
  void set_trigger_value(float value);
  private:
  float _internal_trigger_value() const;
  void _internal_set_trigger_value(float value);
  public:

  // float vel_before = 4;
  void clear_vel_before();
  float vel_before() const;
  void set_vel_before(float value);
  private:
  float _internal_vel_before() const;
  void _internal_set_vel_before(float value);
  public:

  // float vel_after = 5;
  void clear_vel_after();
  float vel_after() const;
  void set_vel_after(float value);
  private:
  float _internal_vel_after() const;
  void _internal_set_vel_after(float value);
  public:

  // @@protoc_insertion_point(class_scope:terra_perceive.SafetyEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rule_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr details_;
  double timestamp_;
  float trigger_value_;
  float vel_before_;
  float vel_after_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_safety_2eproto;
};
// -------------------------------------------------------------------

class SafetyEventLog PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:terra_perceive.SafetyEventLog) */ {
 public:
  inline SafetyEventLog() : SafetyEventLog(nullptr) {};
  virtual ~SafetyEventLog();

  SafetyEventLog(const SafetyEventLog& from);
  SafetyEventLog(SafetyEventLog&& from) noexcept
    : SafetyEventLog() {
    *this = ::std::move(from);
  }

  inline SafetyEventLog& operator=(const SafetyEventLog& from) {
    CopyFrom(from);
    return *this;
  }
  inline SafetyEventLog& operator=(SafetyEventLog&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SafetyEventLog& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SafetyEventLog* internal_default_instance() {
    return reinterpret_cast<const SafetyEventLog*>(
               &_SafetyEventLog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SafetyEventLog& a, SafetyEventLog& b) {
    a.Swap(&b);
  }
  inline void Swap(SafetyEventLog* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SafetyEventLog* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SafetyEventLog* New() const final {
    return CreateMaybeMessage<SafetyEventLog>(nullptr);
  }

  SafetyEventLog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SafetyEventLog>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SafetyEventLog& from);
  void MergeFrom(const SafetyEventLog& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SafetyEventLog* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "terra_perceive.SafetyEventLog";
  }
  protected:
  explicit SafetyEventLog(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_safety_2eproto);
    return ::descriptor_table_safety_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .terra_perceive.SafetyEvent events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::terra_perceive::SafetyEvent* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::SafetyEvent >*
      mutable_events();
  private:
  const ::terra_perceive::SafetyEvent& _internal_events(int index) const;
  ::terra_perceive::SafetyEvent* _internal_add_events();
  public:
  const ::terra_perceive::SafetyEvent& events(int index) const;
  ::terra_perceive::SafetyEvent* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::SafetyEvent >&
      events() const;

  // @@protoc_insertion_point(class_scope:terra_perceive.SafetyEventLog)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::SafetyEvent > events_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_safety_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SafeVelocity

// double timestamp = 1;
inline void SafeVelocity::clear_timestamp() {
  timestamp_ = 0;
}
inline double SafeVelocity::_internal_timestamp() const {
  return timestamp_;
}
inline double SafeVelocity::timestamp() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafeVelocity.timestamp)
  return _internal_timestamp();
}
inline void SafeVelocity::_internal_set_timestamp(double value) {
  
  timestamp_ = value;
}
inline void SafeVelocity::set_timestamp(double value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafeVelocity.timestamp)
}

// float linear_x = 2;
inline void SafeVelocity::clear_linear_x() {
  linear_x_ = 0;
}
inline float SafeVelocity::_internal_linear_x() const {
  return linear_x_;
}
inline float SafeVelocity::linear_x() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafeVelocity.linear_x)
  return _internal_linear_x();
}
inline void SafeVelocity::_internal_set_linear_x(float value) {
  
  linear_x_ = value;
}
inline void SafeVelocity::set_linear_x(float value) {
  _internal_set_linear_x(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafeVelocity.linear_x)
}

// float angular_z = 3;
inline void SafeVelocity::clear_angular_z() {
  angular_z_ = 0;
}
inline float SafeVelocity::_internal_angular_z() const {
  return angular_z_;
}
inline float SafeVelocity::angular_z() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafeVelocity.angular_z)
  return _internal_angular_z();
}
inline void SafeVelocity::_internal_set_angular_z(float value) {
  
  angular_z_ = value;
}
inline void SafeVelocity::set_angular_z(float value) {
  _internal_set_angular_z(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafeVelocity.angular_z)
}

// string active_rule = 4;
inline void SafeVelocity::clear_active_rule() {
  active_rule_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SafeVelocity::active_rule() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafeVelocity.active_rule)
  return _internal_active_rule();
}
inline void SafeVelocity::set_active_rule(const std::string& value) {
  _internal_set_active_rule(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafeVelocity.active_rule)
}
inline std::string* SafeVelocity::mutable_active_rule() {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SafeVelocity.active_rule)
  return _internal_mutable_active_rule();
}
inline const std::string& SafeVelocity::_internal_active_rule() const {
  return active_rule_.Get();
}
inline void SafeVelocity::_internal_set_active_rule(const std::string& value) {
  
  active_rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SafeVelocity::set_active_rule(std::string&& value) {
  
  active_rule_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:terra_perceive.SafeVelocity.active_rule)
}
inline void SafeVelocity::set_active_rule(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  active_rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:terra_perceive.SafeVelocity.active_rule)
}
inline void SafeVelocity::set_active_rule(const char* value,
    size_t size) {
  
  active_rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:terra_perceive.SafeVelocity.active_rule)
}
inline std::string* SafeVelocity::_internal_mutable_active_rule() {
  
  return active_rule_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SafeVelocity::release_active_rule() {
  // @@protoc_insertion_point(field_release:terra_perceive.SafeVelocity.active_rule)
  return active_rule_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SafeVelocity::set_allocated_active_rule(std::string* active_rule) {
  if (active_rule != nullptr) {
    
  } else {
    
  }
  active_rule_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), active_rule,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:terra_perceive.SafeVelocity.active_rule)
}
inline std::string* SafeVelocity::unsafe_arena_release_active_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:terra_perceive.SafeVelocity.active_rule)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return active_rule_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SafeVelocity::unsafe_arena_set_allocated_active_rule(
    std::string* active_rule) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (active_rule != nullptr) {
    
  } else {
    
  }
  active_rule_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      active_rule, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:terra_perceive.SafeVelocity.active_rule)
}

// string reason = 5;
inline void SafeVelocity::clear_reason() {
  reason_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SafeVelocity::reason() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafeVelocity.reason)
  return _internal_reason();
}
inline void SafeVelocity::set_reason(const std::string& value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafeVelocity.reason)
}
inline std::string* SafeVelocity::mutable_reason() {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SafeVelocity.reason)
  return _internal_mutable_reason();
}
inline const std::string& SafeVelocity::_internal_reason() const {
  return reason_.Get();
}
inline void SafeVelocity::_internal_set_reason(const std::string& value) {
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SafeVelocity::set_reason(std::string&& value) {
  
  reason_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:terra_perceive.SafeVelocity.reason)
}
inline void SafeVelocity::set_reason(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:terra_perceive.SafeVelocity.reason)
}
inline void SafeVelocity::set_reason(const char* value,
    size_t size) {
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:terra_perceive.SafeVelocity.reason)
}
inline std::string* SafeVelocity::_internal_mutable_reason() {
  
  return reason_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SafeVelocity::release_reason() {
  // @@protoc_insertion_point(field_release:terra_perceive.SafeVelocity.reason)
  return reason_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SafeVelocity::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  reason_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reason,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:terra_perceive.SafeVelocity.reason)
}
inline std::string* SafeVelocity::unsafe_arena_release_reason() {
  // @@protoc_insertion_point(field_unsafe_arena_release:terra_perceive.SafeVelocity.reason)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return reason_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SafeVelocity::unsafe_arena_set_allocated_reason(
    std::string* reason) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (reason != nullptr) {
    
  } else {
    
  }
  reason_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      reason, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:terra_perceive.SafeVelocity.reason)
}

// -------------------------------------------------------------------

// SafetyEvent

// double timestamp = 1;
inline void SafetyEvent::clear_timestamp() {
  timestamp_ = 0;
}
inline double SafetyEvent::_internal_timestamp() const {
  return timestamp_;
}
inline double SafetyEvent::timestamp() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.timestamp)
  return _internal_timestamp();
}
inline void SafetyEvent::_internal_set_timestamp(double value) {
  
  timestamp_ = value;
}
inline void SafetyEvent::set_timestamp(double value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.timestamp)
}

// string rule = 2;
inline void SafetyEvent::clear_rule() {
  rule_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SafetyEvent::rule() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.rule)
  return _internal_rule();
}
inline void SafetyEvent::set_rule(const std::string& value) {
  _internal_set_rule(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.rule)
}
inline std::string* SafetyEvent::mutable_rule() {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SafetyEvent.rule)
  return _internal_mutable_rule();
}
inline const std::string& SafetyEvent::_internal_rule() const {
  return rule_.Get();
}
inline void SafetyEvent::_internal_set_rule(const std::string& value) {
  
  rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SafetyEvent::set_rule(std::string&& value) {
  
  rule_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:terra_perceive.SafetyEvent.rule)
}
inline void SafetyEvent::set_rule(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:terra_perceive.SafetyEvent.rule)
}
inline void SafetyEvent::set_rule(const char* value,
    size_t size) {
  
  rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:terra_perceive.SafetyEvent.rule)
}
inline std::string* SafetyEvent::_internal_mutable_rule() {
  
  return rule_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SafetyEvent::release_rule() {
  // @@protoc_insertion_point(field_release:terra_perceive.SafetyEvent.rule)
  return rule_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SafetyEvent::set_allocated_rule(std::string* rule) {
  if (rule != nullptr) {
    
  } else {
    
  }
  rule_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rule,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:terra_perceive.SafetyEvent.rule)
}
inline std::string* SafetyEvent::unsafe_arena_release_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:terra_perceive.SafetyEvent.rule)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return rule_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SafetyEvent::unsafe_arena_set_allocated_rule(
    std::string* rule) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (rule != nullptr) {
    
  } else {
    
  }
  rule_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      rule, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:terra_perceive.SafetyEvent.rule)
}

// float trigger_value = 3;
inline void SafetyEvent::clear_trigger_value() {
  trigger_value_ = 0;
}
inline float SafetyEvent::_internal_trigger_value() const {
  return trigger_value_;
}
inline float SafetyEvent::trigger_value() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.trigger_value)
  return _internal_trigger_value();
}
inline void SafetyEvent::_internal_set_trigger_value(float value) {
  
  trigger_value_ = value;
}
inline void SafetyEvent::set_trigger_value(float value) {
  _internal_set_trigger_value(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.trigger_value)
}

// float vel_before = 4;
inline void SafetyEvent::clear_vel_before() {
  vel_before_ = 0;
}
inline float SafetyEvent::_internal_vel_before() const {
  return vel_before_;
}
inline float SafetyEvent::vel_before() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.vel_before)
  return _internal_vel_before();
}
inline void SafetyEvent::_internal_set_vel_before(float value) {
  
  vel_before_ = value;
}
inline void SafetyEvent::set_vel_before(float value) {
  _internal_set_vel_before(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.vel_before)
}

// float vel_after = 5;
inline void SafetyEvent::clear_vel_after() {
  vel_after_ = 0;
}
inline float SafetyEvent::_internal_vel_after() const {
  return vel_after_;
}
inline float SafetyEvent::vel_after() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.vel_after)
  return _internal_vel_after();
}
inline void SafetyEvent::_internal_set_vel_after(float value) {
  
  vel_after_ = value;
}
inline void SafetyEvent::set_vel_after(float value) {
  _internal_set_vel_after(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.vel_after)
}

// string details = 6;
inline void SafetyEvent::clear_details() {
  details_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SafetyEvent::details() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEvent.details)
  return _internal_details();
}
inline void SafetyEvent::set_details(const std::string& value) {
  _internal_set_details(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SafetyEvent.details)
}
inline std::string* SafetyEvent::mutable_details() {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SafetyEvent.details)
  return _internal_mutable_details();
}
inline const std::string& SafetyEvent::_internal_details() const {
  return details_.Get();
}
inline void SafetyEvent::_internal_set_details(const std::string& value) {
  
  details_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SafetyEvent::set_details(std::string&& value) {
  
  details_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:terra_perceive.SafetyEvent.details)
}
inline void SafetyEvent::set_details(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  details_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:terra_perceive.SafetyEvent.details)
}
inline void SafetyEvent::set_details(const char* value,
    size_t size) {
  
  details_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:terra_perceive.SafetyEvent.details)
}
inline std::string* SafetyEvent::_internal_mutable_details() {
  
  return details_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SafetyEvent::release_details() {
  // @@protoc_insertion_point(field_release:terra_perceive.SafetyEvent.details)
  return details_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SafetyEvent::set_allocated_details(std::string* details) {
  if (details != nullptr) {
    
  } else {
    
  }
  details_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), details,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:terra_perceive.SafetyEvent.details)
}
inline std::string* SafetyEvent::unsafe_arena_release_details() {
  // @@protoc_insertion_point(field_unsafe_arena_release:terra_perceive.SafetyEvent.details)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return details_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SafetyEvent::unsafe_arena_set_allocated_details(
    std::string* details) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (details != nullptr) {
    
  } else {
    
  }
  details_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      details, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:terra_perceive.SafetyEvent.details)
}

// -------------------------------------------------------------------

// SafetyEventLog

// repeated .terra_perceive.SafetyEvent events = 1;
inline int SafetyEventLog::_internal_events_size() const {
  return events_.size();
}
inline int SafetyEventLog::events_size() const {
  return _internal_events_size();
}
inline void SafetyEventLog::clear_events() {
  events_.Clear();
}
inline ::terra_perceive::SafetyEvent* SafetyEventLog::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SafetyEventLog.events)
  return events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::SafetyEvent >*
SafetyEventLog::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:terra_perceive.SafetyEventLog.events)
  return &events_;
}
inline const ::terra_perceive::SafetyEvent& SafetyEventLog::_internal_events(int index) const {
  return events_.Get(index);
}
inline const ::terra_perceive::SafetyEvent& SafetyEventLog::events(int index) const {
  // @@protoc_insertion_point(field_get:terra_perceive.SafetyEventLog.events)
  return _internal_events(index);
}
inline ::terra_perceive::SafetyEvent* SafetyEventLog::_internal_add_events() {
  return events_.Add();
}
inline ::terra_perceive::SafetyEvent* SafetyEventLog::add_events() {
  // @@protoc_insertion_point(field_add:terra_perceive.SafetyEventLog.events)
  return _internal_add_events();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::SafetyEvent >&
SafetyEventLog::events() const {
  // @@protoc_insertion_point(field_list:terra_perceive.SafetyEventLog.events)
  return events_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace terra_perceive

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_safety_2eproto
