// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: safety.proto

#include "safety.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_safety_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SafetyEvent_safety_2eproto;
namespace terra_perceive {
class SafeVelocityDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SafeVelocity> _instance;
} _SafeVelocity_default_instance_;
class SafetyEventDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SafetyEvent> _instance;
} _SafetyEvent_default_instance_;
class SafetyEventLogDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SafetyEventLog> _instance;
} _SafetyEventLog_default_instance_;
}  // namespace terra_perceive
static void InitDefaultsscc_info_SafeVelocity_safety_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::terra_perceive::_SafeVelocity_default_instance_;
    new (ptr) ::terra_perceive::SafeVelocity();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::terra_perceive::SafeVelocity::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SafeVelocity_safety_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SafeVelocity_safety_2eproto}, {}};

static void InitDefaultsscc_info_SafetyEvent_safety_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::terra_perceive::_SafetyEvent_default_instance_;
    new (ptr) ::terra_perceive::SafetyEvent();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::terra_perceive::SafetyEvent::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SafetyEvent_safety_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SafetyEvent_safety_2eproto}, {}};

static void InitDefaultsscc_info_SafetyEventLog_safety_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::terra_perceive::_SafetyEventLog_default_instance_;
    new (ptr) ::terra_perceive::SafetyEventLog();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::terra_perceive::SafetyEventLog::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SafetyEventLog_safety_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SafetyEventLog_safety_2eproto}, {
      &scc_info_SafetyEvent_safety_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_safety_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_safety_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_safety_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_safety_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, timestamp_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, linear_x_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, angular_z_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, active_rule_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafeVelocity, reason_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, timestamp_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, rule_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, trigger_value_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, vel_before_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, vel_after_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEvent, details_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEventLog, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SafetyEventLog, events_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::terra_perceive::SafeVelocity)},
  { 10, -1, sizeof(::terra_perceive::SafetyEvent)},
  { 21, -1, sizeof(::terra_perceive::SafetyEventLog)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::terra_perceive::_SafeVelocity_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::terra_perceive::_SafetyEvent_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::terra_perceive::_SafetyEventLog_default_instance_),
};

const char descriptor_table_protodef_safety_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014safety.proto\022\016terra_perceive\"k\n\014SafeVe"
  "locity\022\021\n\ttimestamp\030\001 \001(\001\022\020\n\010linear_x\030\002 "
  "\001(\002\022\021\n\tangular_z\030\003 \001(\002\022\023\n\013active_rule\030\004 "
  "\001(\t\022\016\n\006reason\030\005 \001(\t\"}\n\013SafetyEvent\022\021\n\tti"
  "mestamp\030\001 \001(\001\022\014\n\004rule\030\002 \001(\t\022\025\n\rtrigger_v"
  "alue\030\003 \001(\002\022\022\n\nvel_before\030\004 \001(\002\022\021\n\tvel_af"
  "ter\030\005 \001(\002\022\017\n\007details\030\006 \001(\t\"=\n\016SafetyEven"
  "tLog\022+\n\006events\030\001 \003(\0132\033.terra_perceive.Sa"
  "fetyEventb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_safety_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_safety_2eproto_sccs[3] = {
  &scc_info_SafeVelocity_safety_2eproto.base,
  &scc_info_SafetyEvent_safety_2eproto.base,
  &scc_info_SafetyEventLog_safety_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_safety_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_safety_2eproto = {
  false, false, descriptor_table_protodef_safety_2eproto, "safety.proto", 337,
  &descriptor_table_safety_2eproto_once, descriptor_table_safety_2eproto_sccs, descriptor_table_safety_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_safety_2eproto::offsets,
  file_level_metadata_safety_2eproto, 3, file_level_enum_descriptors_safety_2eproto, file_level_service_descriptors_safety_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_safety_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_safety_2eproto)), true);
namespace terra_perceive {

// ===================================================================

void SafeVelocity::InitAsDefaultInstance() {
}
class SafeVelocity::_Internal {
 public:
};

SafeVelocity::SafeVelocity(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:terra_perceive.SafeVelocity)
}
SafeVelocity::SafeVelocity(const SafeVelocity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  active_rule_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_active_rule().empty()) {
    active_rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_active_rule(),
      GetArena());
  }
  reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reason().empty()) {
    reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_reason(),
      GetArena());
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&angular_z_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(angular_z_));
  // @@protoc_insertion_point(copy_constructor:terra_perceive.SafeVelocity)
}

void SafeVelocity::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SafeVelocity_safety_2eproto.base);
  active_rule_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&angular_z_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(angular_z_));
}

SafeVelocity::~SafeVelocity() {
  // @@protoc_insertion_point(destructor:terra_perceive.SafeVelocity)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SafeVelocity::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  active_rule_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reason_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SafeVelocity::ArenaDtor(void* object) {
  SafeVelocity* _this = reinterpret_cast< SafeVelocity* >(object);
  (void)_this;
}
void SafeVelocity::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SafeVelocity::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SafeVelocity& SafeVelocity::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SafeVelocity_safety_2eproto.base);
  return *internal_default_instance();
}


void SafeVelocity::Clear() {
// @@protoc_insertion_point(message_clear_start:terra_perceive.SafeVelocity)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  active_rule_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  reason_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&angular_z_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(angular_z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SafeVelocity::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // float linear_x = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          linear_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float angular_z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          angular_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // string active_rule = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_active_rule();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "terra_perceive.SafeVelocity.active_rule"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reason = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_reason();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "terra_perceive.SafeVelocity.reason"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SafeVelocity::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terra_perceive.SafeVelocity)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_timestamp(), target);
  }

  // float linear_x = 2;
  if (!(this->linear_x() <= 0 && this->linear_x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_linear_x(), target);
  }

  // float angular_z = 3;
  if (!(this->angular_z() <= 0 && this->angular_z() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_angular_z(), target);
  }

  // string active_rule = 4;
  if (this->active_rule().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_active_rule().data(), static_cast<int>(this->_internal_active_rule().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "terra_perceive.SafeVelocity.active_rule");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_active_rule(), target);
  }

  // string reason = 5;
  if (this->reason().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "terra_perceive.SafeVelocity.reason");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terra_perceive.SafeVelocity)
  return target;
}

size_t SafeVelocity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terra_perceive.SafeVelocity)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string active_rule = 4;
  if (this->active_rule().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_active_rule());
  }

  // string reason = 5;
  if (this->reason().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    total_size += 1 + 8;
  }

  // float linear_x = 2;
  if (!(this->linear_x() <= 0 && this->linear_x() >= 0)) {
    total_size += 1 + 4;
  }

  // float angular_z = 3;
  if (!(this->angular_z() <= 0 && this->angular_z() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SafeVelocity::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:terra_perceive.SafeVelocity)
  GOOGLE_DCHECK_NE(&from, this);
  const SafeVelocity* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SafeVelocity>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:terra_perceive.SafeVelocity)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:terra_perceive.SafeVelocity)
    MergeFrom(*source);
  }
}

void SafeVelocity::MergeFrom(const SafeVelocity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:terra_perceive.SafeVelocity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.active_rule().size() > 0) {
    _internal_set_active_rule(from._internal_active_rule());
  }
  if (from.reason().size() > 0) {
    _internal_set_reason(from._internal_reason());
  }
  if (!(from.timestamp() <= 0 && from.timestamp() >= 0)) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  if (!(from.linear_x() <= 0 && from.linear_x() >= 0)) {
    _internal_set_linear_x(from._internal_linear_x());
  }
  if (!(from.angular_z() <= 0 && from.angular_z() >= 0)) {
    _internal_set_angular_z(from._internal_angular_z());
  }
}

void SafeVelocity::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:terra_perceive.SafeVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SafeVelocity::CopyFrom(const SafeVelocity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terra_perceive.SafeVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SafeVelocity::IsInitialized() const {
  return true;
}

void SafeVelocity::InternalSwap(SafeVelocity* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  active_rule_.Swap(&other->active_rule_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  reason_.Swap(&other->reason_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SafeVelocity, angular_z_)
      + sizeof(SafeVelocity::angular_z_)
      - PROTOBUF_FIELD_OFFSET(SafeVelocity, timestamp_)>(
          reinterpret_cast<char*>(&timestamp_),
          reinterpret_cast<char*>(&other->timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SafeVelocity::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SafetyEvent::InitAsDefaultInstance() {
}
class SafetyEvent::_Internal {
 public:
};

SafetyEvent::SafetyEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:terra_perceive.SafetyEvent)
}
SafetyEvent::SafetyEvent(const SafetyEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  rule_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_rule().empty()) {
    rule_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_rule(),
      GetArena());
  }
  details_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_details().empty()) {
    details_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_details(),
      GetArena());
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&vel_after_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(vel_after_));
  // @@protoc_insertion_point(copy_constructor:terra_perceive.SafetyEvent)
}

void SafetyEvent::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SafetyEvent_safety_2eproto.base);
  rule_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  details_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&vel_after_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(vel_after_));
}

SafetyEvent::~SafetyEvent() {
  // @@protoc_insertion_point(destructor:terra_perceive.SafetyEvent)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SafetyEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  rule_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  details_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SafetyEvent::ArenaDtor(void* object) {
  SafetyEvent* _this = reinterpret_cast< SafetyEvent* >(object);
  (void)_this;
}
void SafetyEvent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SafetyEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SafetyEvent& SafetyEvent::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SafetyEvent_safety_2eproto.base);
  return *internal_default_instance();
}


void SafetyEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:terra_perceive.SafetyEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rule_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  details_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&vel_after_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(vel_after_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SafetyEvent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string rule = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_rule();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "terra_perceive.SafetyEvent.rule"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float trigger_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          trigger_value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float vel_before = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          vel_before_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float vel_after = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          vel_after_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // string details = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_details();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "terra_perceive.SafetyEvent.details"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SafetyEvent::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terra_perceive.SafetyEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_timestamp(), target);
  }

  // string rule = 2;
  if (this->rule().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rule().data(), static_cast<int>(this->_internal_rule().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "terra_perceive.SafetyEvent.rule");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_rule(), target);
  }

  // float trigger_value = 3;
  if (!(this->trigger_value() <= 0 && this->trigger_value() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_trigger_value(), target);
  }

  // float vel_before = 4;
  if (!(this->vel_before() <= 0 && this->vel_before() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_vel_before(), target);
  }

  // float vel_after = 5;
  if (!(this->vel_after() <= 0 && this->vel_after() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_vel_after(), target);
  }

  // string details = 6;
  if (this->details().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_details().data(), static_cast<int>(this->_internal_details().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "terra_perceive.SafetyEvent.details");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_details(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terra_perceive.SafetyEvent)
  return target;
}

size_t SafetyEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terra_perceive.SafetyEvent)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string rule = 2;
  if (this->rule().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rule());
  }

  // string details = 6;
  if (this->details().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_details());
  }

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    total_size += 1 + 8;
  }

  // float trigger_value = 3;
  if (!(this->trigger_value() <= 0 && this->trigger_value() >= 0)) {
    total_size += 1 + 4;
  }

  // float vel_before = 4;
  if (!(this->vel_before() <= 0 && this->vel_before() >= 0)) {
    total_size += 1 + 4;
  }

  // float vel_after = 5;
  if (!(this->vel_after() <= 0 && this->vel_after() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SafetyEvent::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:terra_perceive.SafetyEvent)
  GOOGLE_DCHECK_NE(&from, this);
  const SafetyEvent* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SafetyEvent>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:terra_perceive.SafetyEvent)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:terra_perceive.SafetyEvent)
    MergeFrom(*source);
  }
}

void SafetyEvent::MergeFrom(const SafetyEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:terra_perceive.SafetyEvent)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.rule().size() > 0) {
    _internal_set_rule(from._internal_rule());
  }
  if (from.details().size() > 0) {
    _internal_set_details(from._internal_details());
  }
  if (!(from.timestamp() <= 0 && from.timestamp() >= 0)) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  if (!(from.trigger_value() <= 0 && from.trigger_value() >= 0)) {
    _internal_set_trigger_value(from._internal_trigger_value());
  }
  if (!(from.vel_before() <= 0 && from.vel_before() >= 0)) {
    _internal_set_vel_before(from._internal_vel_before());
  }
  if (!(from.vel_after() <= 0 && from.vel_after() >= 0)) {
    _internal_set_vel_after(from._internal_vel_after());
  }
}

void SafetyEvent::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:terra_perceive.SafetyEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SafetyEvent::CopyFrom(const SafetyEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terra_perceive.SafetyEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SafetyEvent::IsInitialized() const {
  return true;
}

void SafetyEvent::InternalSwap(SafetyEvent* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  rule_.Swap(&other->rule_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  details_.Swap(&other->details_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SafetyEvent, vel_after_)
      + sizeof(SafetyEvent::vel_after_)
      - PROTOBUF_FIELD_OFFSET(SafetyEvent, timestamp_)>(
          reinterpret_cast<char*>(&timestamp_),
          reinterpret_cast<char*>(&other->timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SafetyEvent::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SafetyEventLog::InitAsDefaultInstance() {
}
class SafetyEventLog::_Internal {
 public:
};

SafetyEventLog::SafetyEventLog(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  events_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:terra_perceive.SafetyEventLog)
}
SafetyEventLog::SafetyEventLog(const SafetyEventLog& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      events_(from.events_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:terra_perceive.SafetyEventLog)
}

void SafetyEventLog::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SafetyEventLog_safety_2eproto.base);
}

SafetyEventLog::~SafetyEventLog() {
  // @@protoc_insertion_point(destructor:terra_perceive.SafetyEventLog)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SafetyEventLog::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SafetyEventLog::ArenaDtor(void* object) {
  SafetyEventLog* _this = reinterpret_cast< SafetyEventLog* >(object);
  (void)_this;
}
void SafetyEventLog::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SafetyEventLog::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SafetyEventLog& SafetyEventLog::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SafetyEventLog_safety_2eproto.base);
  return *internal_default_instance();
}


void SafetyEventLog::Clear() {
// @@protoc_insertion_point(message_clear_start:terra_perceive.SafetyEventLog)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  events_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SafetyEventLog::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .terra_perceive.SafetyEvent events = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_events(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SafetyEventLog::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terra_perceive.SafetyEventLog)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .terra_perceive.SafetyEvent events = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_events_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_events(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terra_perceive.SafetyEventLog)
  return target;
}

size_t SafetyEventLog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terra_perceive.SafetyEventLog)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .terra_perceive.SafetyEvent events = 1;
  total_size += 1UL * this->_internal_events_size();
  for (const auto& msg : this->events_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SafetyEventLog::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:terra_perceive.SafetyEventLog)
  GOOGLE_DCHECK_NE(&from, this);
  const SafetyEventLog* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SafetyEventLog>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:terra_perceive.SafetyEventLog)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:terra_perceive.SafetyEventLog)
    MergeFrom(*source);
  }
}

void SafetyEventLog::MergeFrom(const SafetyEventLog& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:terra_perceive.SafetyEventLog)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  events_.MergeFrom(from.events_);
}

void SafetyEventLog::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:terra_perceive.SafetyEventLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SafetyEventLog::CopyFrom(const SafetyEventLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terra_perceive.SafetyEventLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SafetyEventLog::IsInitialized() const {
  return true;
}

void SafetyEventLog::InternalSwap(SafetyEventLog* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  events_.InternalSwap(&other->events_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SafetyEventLog::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace terra_perceive
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::terra_perceive::SafeVelocity* Arena::CreateMaybeMessage< ::terra_perceive::SafeVelocity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::terra_perceive::SafeVelocity >(arena);
}
template<> PROTOBUF_NOINLINE ::terra_perceive::SafetyEvent* Arena::CreateMaybeMessage< ::terra_perceive::SafetyEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::terra_perceive::SafetyEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::terra_perceive::SafetyEventLog* Arena::CreateMaybeMessage< ::terra_perceive::SafetyEventLog >(Arena* arena) {
  return Arena::CreateMessageInternal< ::terra_perceive::SafetyEventLog >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
