// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto;
namespace terra_perceive {
class LatencyMetrics;
class LatencyMetricsDefaultTypeInternal;
extern LatencyMetricsDefaultTypeInternal _LatencyMetrics_default_instance_;
class SessionReport;
class SessionReportDefaultTypeInternal;
extern SessionReportDefaultTypeInternal _SessionReport_default_instance_;
}  // namespace terra_perceive
PROTOBUF_NAMESPACE_OPEN
template<> ::terra_perceive::LatencyMetrics* Arena::CreateMaybeMessage<::terra_perceive::LatencyMetrics>(Arena*);
template<> ::terra_perceive::SessionReport* Arena::CreateMaybeMessage<::terra_perceive::SessionReport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace terra_perceive {

// ===================================================================

class LatencyMetrics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:terra_perceive.LatencyMetrics) */ {
 public:
  inline LatencyMetrics() : LatencyMetrics(nullptr) {};
  virtual ~LatencyMetrics();

  LatencyMetrics(const LatencyMetrics& from);
  LatencyMetrics(LatencyMetrics&& from) noexcept
    : LatencyMetrics() {
    *this = ::std::move(from);
  }

  inline LatencyMetrics& operator=(const LatencyMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline LatencyMetrics& operator=(LatencyMetrics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LatencyMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LatencyMetrics* internal_default_instance() {
    return reinterpret_cast<const LatencyMetrics*>(
               &_LatencyMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LatencyMetrics& a, LatencyMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(LatencyMetrics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LatencyMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LatencyMetrics* New() const final {
    return CreateMaybeMessage<LatencyMetrics>(nullptr);
  }

  LatencyMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LatencyMetrics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LatencyMetrics& from);
  void MergeFrom(const LatencyMetrics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LatencyMetrics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "terra_perceive.LatencyMetrics";
  }
  protected:
  explicit LatencyMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_2eproto);
    return ::descriptor_table_telemetry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModuleFieldNumber = 2,
    kTimestampFieldNumber = 1,
    kP50MsFieldNumber = 3,
    kP95MsFieldNumber = 4,
    kP99MsFieldNumber = 5,
    kDropRateFieldNumber = 6,
    kHzActualFieldNumber = 7,
  };
  // string module = 2;
  void clear_module();
  const std::string& module() const;
  void set_module(const std::string& value);
  void set_module(std::string&& value);
  void set_module(const char* value);
  void set_module(const char* value, size_t size);
  std::string* mutable_module();
  std::string* release_module();
  void set_allocated_module(std::string* module);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_module();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_module(
      std::string* module);
  private:
  const std::string& _internal_module() const;
  void _internal_set_module(const std::string& value);
  std::string* _internal_mutable_module();
  public:

  // double timestamp = 1;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);
  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);
  public:

  // float p50_ms = 3;
  void clear_p50_ms();
  float p50_ms() const;
  void set_p50_ms(float value);
  private:
  float _internal_p50_ms() const;
  void _internal_set_p50_ms(float value);
  public:

  // float p95_ms = 4;
  void clear_p95_ms();
  float p95_ms() const;
  void set_p95_ms(float value);
  private:
  float _internal_p95_ms() const;
  void _internal_set_p95_ms(float value);
  public:

  // float p99_ms = 5;
  void clear_p99_ms();
  float p99_ms() const;
  void set_p99_ms(float value);
  private:
  float _internal_p99_ms() const;
  void _internal_set_p99_ms(float value);
  public:

  // float drop_rate = 6;
  void clear_drop_rate();
  float drop_rate() const;
  void set_drop_rate(float value);
  private:
  float _internal_drop_rate() const;
  void _internal_set_drop_rate(float value);
  public:

  // float hz_actual = 7;
  void clear_hz_actual();
  float hz_actual() const;
  void set_hz_actual(float value);
  private:
  float _internal_hz_actual() const;
  void _internal_set_hz_actual(float value);
  public:

  // @@protoc_insertion_point(class_scope:terra_perceive.LatencyMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr module_;
  double timestamp_;
  float p50_ms_;
  float p95_ms_;
  float p99_ms_;
  float drop_rate_;
  float hz_actual_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_telemetry_2eproto;
};
// -------------------------------------------------------------------

class SessionReport PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:terra_perceive.SessionReport) */ {
 public:
  inline SessionReport() : SessionReport(nullptr) {};
  virtual ~SessionReport();

  SessionReport(const SessionReport& from);
  SessionReport(SessionReport&& from) noexcept
    : SessionReport() {
    *this = ::std::move(from);
  }

  inline SessionReport& operator=(const SessionReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionReport& operator=(SessionReport&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SessionReport& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SessionReport* internal_default_instance() {
    return reinterpret_cast<const SessionReport*>(
               &_SessionReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SessionReport& a, SessionReport& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionReport* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SessionReport* New() const final {
    return CreateMaybeMessage<SessionReport>(nullptr);
  }

  SessionReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SessionReport>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SessionReport& from);
  void MergeFrom(const SessionReport& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SessionReport* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "terra_perceive.SessionReport";
  }
  protected:
  explicit SessionReport(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_2eproto);
    return ::descriptor_table_telemetry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModuleMetricsFieldNumber = 9,
    kStartTimeFieldNumber = 1,
    kEndTimeFieldNumber = 2,
    kTotalFramesFieldNumber = 3,
    kTotalDetectionsFieldNumber = 4,
    kTotalSafetyStopsFieldNumber = 5,
    kTotalSafetySlowsFieldNumber = 6,
    kUptimePercentFieldNumber = 7,
    kAreaCoveredM2FieldNumber = 8,
  };
  // repeated .terra_perceive.LatencyMetrics module_metrics = 9;
  int module_metrics_size() const;
  private:
  int _internal_module_metrics_size() const;
  public:
  void clear_module_metrics();
  ::terra_perceive::LatencyMetrics* mutable_module_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::LatencyMetrics >*
      mutable_module_metrics();
  private:
  const ::terra_perceive::LatencyMetrics& _internal_module_metrics(int index) const;
  ::terra_perceive::LatencyMetrics* _internal_add_module_metrics();
  public:
  const ::terra_perceive::LatencyMetrics& module_metrics(int index) const;
  ::terra_perceive::LatencyMetrics* add_module_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::LatencyMetrics >&
      module_metrics() const;

  // double start_time = 1;
  void clear_start_time();
  double start_time() const;
  void set_start_time(double value);
  private:
  double _internal_start_time() const;
  void _internal_set_start_time(double value);
  public:

  // double end_time = 2;
  void clear_end_time();
  double end_time() const;
  void set_end_time(double value);
  private:
  double _internal_end_time() const;
  void _internal_set_end_time(double value);
  public:

  // uint32 total_frames = 3;
  void clear_total_frames();
  ::PROTOBUF_NAMESPACE_ID::uint32 total_frames() const;
  void set_total_frames(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_total_frames() const;
  void _internal_set_total_frames(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 total_detections = 4;
  void clear_total_detections();
  ::PROTOBUF_NAMESPACE_ID::uint32 total_detections() const;
  void set_total_detections(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_total_detections() const;
  void _internal_set_total_detections(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 total_safety_stops = 5;
  void clear_total_safety_stops();
  ::PROTOBUF_NAMESPACE_ID::uint32 total_safety_stops() const;
  void set_total_safety_stops(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_total_safety_stops() const;
  void _internal_set_total_safety_stops(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 total_safety_slows = 6;
  void clear_total_safety_slows();
  ::PROTOBUF_NAMESPACE_ID::uint32 total_safety_slows() const;
  void set_total_safety_slows(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_total_safety_slows() const;
  void _internal_set_total_safety_slows(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float uptime_percent = 7;
  void clear_uptime_percent();
  float uptime_percent() const;
  void set_uptime_percent(float value);
  private:
  float _internal_uptime_percent() const;
  void _internal_set_uptime_percent(float value);
  public:

  // float area_covered_m2 = 8;
  void clear_area_covered_m2();
  float area_covered_m2() const;
  void set_area_covered_m2(float value);
  private:
  float _internal_area_covered_m2() const;
  void _internal_set_area_covered_m2(float value);
  public:

  // @@protoc_insertion_point(class_scope:terra_perceive.SessionReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::LatencyMetrics > module_metrics_;
  double start_time_;
  double end_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 total_frames_;
  ::PROTOBUF_NAMESPACE_ID::uint32 total_detections_;
  ::PROTOBUF_NAMESPACE_ID::uint32 total_safety_stops_;
  ::PROTOBUF_NAMESPACE_ID::uint32 total_safety_slows_;
  float uptime_percent_;
  float area_covered_m2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_telemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LatencyMetrics

// double timestamp = 1;
inline void LatencyMetrics::clear_timestamp() {
  timestamp_ = 0;
}
inline double LatencyMetrics::_internal_timestamp() const {
  return timestamp_;
}
inline double LatencyMetrics::timestamp() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.timestamp)
  return _internal_timestamp();
}
inline void LatencyMetrics::_internal_set_timestamp(double value) {
  
  timestamp_ = value;
}
inline void LatencyMetrics::set_timestamp(double value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.timestamp)
}

// string module = 2;
inline void LatencyMetrics::clear_module() {
  module_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LatencyMetrics::module() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.module)
  return _internal_module();
}
inline void LatencyMetrics::set_module(const std::string& value) {
  _internal_set_module(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.module)
}
inline std::string* LatencyMetrics::mutable_module() {
  // @@protoc_insertion_point(field_mutable:terra_perceive.LatencyMetrics.module)
  return _internal_mutable_module();
}
inline const std::string& LatencyMetrics::_internal_module() const {
  return module_.Get();
}
inline void LatencyMetrics::_internal_set_module(const std::string& value) {
  
  module_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LatencyMetrics::set_module(std::string&& value) {
  
  module_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:terra_perceive.LatencyMetrics.module)
}
inline void LatencyMetrics::set_module(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  module_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:terra_perceive.LatencyMetrics.module)
}
inline void LatencyMetrics::set_module(const char* value,
    size_t size) {
  
  module_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:terra_perceive.LatencyMetrics.module)
}
inline std::string* LatencyMetrics::_internal_mutable_module() {
  
  return module_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LatencyMetrics::release_module() {
  // @@protoc_insertion_point(field_release:terra_perceive.LatencyMetrics.module)
  return module_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LatencyMetrics::set_allocated_module(std::string* module) {
  if (module != nullptr) {
    
  } else {
    
  }
  module_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), module,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:terra_perceive.LatencyMetrics.module)
}
inline std::string* LatencyMetrics::unsafe_arena_release_module() {
  // @@protoc_insertion_point(field_unsafe_arena_release:terra_perceive.LatencyMetrics.module)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return module_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LatencyMetrics::unsafe_arena_set_allocated_module(
    std::string* module) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (module != nullptr) {
    
  } else {
    
  }
  module_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      module, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:terra_perceive.LatencyMetrics.module)
}

// float p50_ms = 3;
inline void LatencyMetrics::clear_p50_ms() {
  p50_ms_ = 0;
}
inline float LatencyMetrics::_internal_p50_ms() const {
  return p50_ms_;
}
inline float LatencyMetrics::p50_ms() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.p50_ms)
  return _internal_p50_ms();
}
inline void LatencyMetrics::_internal_set_p50_ms(float value) {
  
  p50_ms_ = value;
}
inline void LatencyMetrics::set_p50_ms(float value) {
  _internal_set_p50_ms(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.p50_ms)
}

// float p95_ms = 4;
inline void LatencyMetrics::clear_p95_ms() {
  p95_ms_ = 0;
}
inline float LatencyMetrics::_internal_p95_ms() const {
  return p95_ms_;
}
inline float LatencyMetrics::p95_ms() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.p95_ms)
  return _internal_p95_ms();
}
inline void LatencyMetrics::_internal_set_p95_ms(float value) {
  
  p95_ms_ = value;
}
inline void LatencyMetrics::set_p95_ms(float value) {
  _internal_set_p95_ms(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.p95_ms)
}

// float p99_ms = 5;
inline void LatencyMetrics::clear_p99_ms() {
  p99_ms_ = 0;
}
inline float LatencyMetrics::_internal_p99_ms() const {
  return p99_ms_;
}
inline float LatencyMetrics::p99_ms() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.p99_ms)
  return _internal_p99_ms();
}
inline void LatencyMetrics::_internal_set_p99_ms(float value) {
  
  p99_ms_ = value;
}
inline void LatencyMetrics::set_p99_ms(float value) {
  _internal_set_p99_ms(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.p99_ms)
}

// float drop_rate = 6;
inline void LatencyMetrics::clear_drop_rate() {
  drop_rate_ = 0;
}
inline float LatencyMetrics::_internal_drop_rate() const {
  return drop_rate_;
}
inline float LatencyMetrics::drop_rate() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.drop_rate)
  return _internal_drop_rate();
}
inline void LatencyMetrics::_internal_set_drop_rate(float value) {
  
  drop_rate_ = value;
}
inline void LatencyMetrics::set_drop_rate(float value) {
  _internal_set_drop_rate(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.drop_rate)
}

// float hz_actual = 7;
inline void LatencyMetrics::clear_hz_actual() {
  hz_actual_ = 0;
}
inline float LatencyMetrics::_internal_hz_actual() const {
  return hz_actual_;
}
inline float LatencyMetrics::hz_actual() const {
  // @@protoc_insertion_point(field_get:terra_perceive.LatencyMetrics.hz_actual)
  return _internal_hz_actual();
}
inline void LatencyMetrics::_internal_set_hz_actual(float value) {
  
  hz_actual_ = value;
}
inline void LatencyMetrics::set_hz_actual(float value) {
  _internal_set_hz_actual(value);
  // @@protoc_insertion_point(field_set:terra_perceive.LatencyMetrics.hz_actual)
}

// -------------------------------------------------------------------

// SessionReport

// double start_time = 1;
inline void SessionReport::clear_start_time() {
  start_time_ = 0;
}
inline double SessionReport::_internal_start_time() const {
  return start_time_;
}
inline double SessionReport::start_time() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.start_time)
  return _internal_start_time();
}
inline void SessionReport::_internal_set_start_time(double value) {
  
  start_time_ = value;
}
inline void SessionReport::set_start_time(double value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.start_time)
}

// double end_time = 2;
inline void SessionReport::clear_end_time() {
  end_time_ = 0;
}
inline double SessionReport::_internal_end_time() const {
  return end_time_;
}
inline double SessionReport::end_time() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.end_time)
  return _internal_end_time();
}
inline void SessionReport::_internal_set_end_time(double value) {
  
  end_time_ = value;
}
inline void SessionReport::set_end_time(double value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.end_time)
}

// uint32 total_frames = 3;
inline void SessionReport::clear_total_frames() {
  total_frames_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::_internal_total_frames() const {
  return total_frames_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::total_frames() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.total_frames)
  return _internal_total_frames();
}
inline void SessionReport::_internal_set_total_frames(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  total_frames_ = value;
}
inline void SessionReport::set_total_frames(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_total_frames(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.total_frames)
}

// uint32 total_detections = 4;
inline void SessionReport::clear_total_detections() {
  total_detections_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::_internal_total_detections() const {
  return total_detections_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::total_detections() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.total_detections)
  return _internal_total_detections();
}
inline void SessionReport::_internal_set_total_detections(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  total_detections_ = value;
}
inline void SessionReport::set_total_detections(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_total_detections(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.total_detections)
}

// uint32 total_safety_stops = 5;
inline void SessionReport::clear_total_safety_stops() {
  total_safety_stops_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::_internal_total_safety_stops() const {
  return total_safety_stops_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::total_safety_stops() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.total_safety_stops)
  return _internal_total_safety_stops();
}
inline void SessionReport::_internal_set_total_safety_stops(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  total_safety_stops_ = value;
}
inline void SessionReport::set_total_safety_stops(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_total_safety_stops(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.total_safety_stops)
}

// uint32 total_safety_slows = 6;
inline void SessionReport::clear_total_safety_slows() {
  total_safety_slows_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::_internal_total_safety_slows() const {
  return total_safety_slows_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SessionReport::total_safety_slows() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.total_safety_slows)
  return _internal_total_safety_slows();
}
inline void SessionReport::_internal_set_total_safety_slows(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  total_safety_slows_ = value;
}
inline void SessionReport::set_total_safety_slows(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_total_safety_slows(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.total_safety_slows)
}

// float uptime_percent = 7;
inline void SessionReport::clear_uptime_percent() {
  uptime_percent_ = 0;
}
inline float SessionReport::_internal_uptime_percent() const {
  return uptime_percent_;
}
inline float SessionReport::uptime_percent() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.uptime_percent)
  return _internal_uptime_percent();
}
inline void SessionReport::_internal_set_uptime_percent(float value) {
  
  uptime_percent_ = value;
}
inline void SessionReport::set_uptime_percent(float value) {
  _internal_set_uptime_percent(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.uptime_percent)
}

// float area_covered_m2 = 8;
inline void SessionReport::clear_area_covered_m2() {
  area_covered_m2_ = 0;
}
inline float SessionReport::_internal_area_covered_m2() const {
  return area_covered_m2_;
}
inline float SessionReport::area_covered_m2() const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.area_covered_m2)
  return _internal_area_covered_m2();
}
inline void SessionReport::_internal_set_area_covered_m2(float value) {
  
  area_covered_m2_ = value;
}
inline void SessionReport::set_area_covered_m2(float value) {
  _internal_set_area_covered_m2(value);
  // @@protoc_insertion_point(field_set:terra_perceive.SessionReport.area_covered_m2)
}

// repeated .terra_perceive.LatencyMetrics module_metrics = 9;
inline int SessionReport::_internal_module_metrics_size() const {
  return module_metrics_.size();
}
inline int SessionReport::module_metrics_size() const {
  return _internal_module_metrics_size();
}
inline void SessionReport::clear_module_metrics() {
  module_metrics_.Clear();
}
inline ::terra_perceive::LatencyMetrics* SessionReport::mutable_module_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:terra_perceive.SessionReport.module_metrics)
  return module_metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::LatencyMetrics >*
SessionReport::mutable_module_metrics() {
  // @@protoc_insertion_point(field_mutable_list:terra_perceive.SessionReport.module_metrics)
  return &module_metrics_;
}
inline const ::terra_perceive::LatencyMetrics& SessionReport::_internal_module_metrics(int index) const {
  return module_metrics_.Get(index);
}
inline const ::terra_perceive::LatencyMetrics& SessionReport::module_metrics(int index) const {
  // @@protoc_insertion_point(field_get:terra_perceive.SessionReport.module_metrics)
  return _internal_module_metrics(index);
}
inline ::terra_perceive::LatencyMetrics* SessionReport::_internal_add_module_metrics() {
  return module_metrics_.Add();
}
inline ::terra_perceive::LatencyMetrics* SessionReport::add_module_metrics() {
  // @@protoc_insertion_point(field_add:terra_perceive.SessionReport.module_metrics)
  return _internal_add_module_metrics();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::terra_perceive::LatencyMetrics >&
SessionReport::module_metrics() const {
  // @@protoc_insertion_point(field_list:terra_perceive.SessionReport.module_metrics)
  return module_metrics_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace terra_perceive

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
