// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#include "telemetry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LatencyMetrics_telemetry_2eproto;
namespace terra_perceive {
class LatencyMetricsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LatencyMetrics> _instance;
} _LatencyMetrics_default_instance_;
class SessionReportDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SessionReport> _instance;
} _SessionReport_default_instance_;
}  // namespace terra_perceive
static void InitDefaultsscc_info_LatencyMetrics_telemetry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::terra_perceive::_LatencyMetrics_default_instance_;
    new (ptr) ::terra_perceive::LatencyMetrics();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::terra_perceive::LatencyMetrics::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LatencyMetrics_telemetry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LatencyMetrics_telemetry_2eproto}, {}};

static void InitDefaultsscc_info_SessionReport_telemetry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::terra_perceive::_SessionReport_default_instance_;
    new (ptr) ::terra_perceive::SessionReport();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::terra_perceive::SessionReport::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SessionReport_telemetry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SessionReport_telemetry_2eproto}, {
      &scc_info_LatencyMetrics_telemetry_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_telemetry_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_telemetry_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_telemetry_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_telemetry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, timestamp_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, module_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, p50_ms_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, p95_ms_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, p99_ms_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, drop_rate_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::LatencyMetrics, hz_actual_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, start_time_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, end_time_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, total_frames_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, total_detections_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, total_safety_stops_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, total_safety_slows_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, uptime_percent_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, area_covered_m2_),
  PROTOBUF_FIELD_OFFSET(::terra_perceive::SessionReport, module_metrics_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::terra_perceive::LatencyMetrics)},
  { 12, -1, sizeof(::terra_perceive::SessionReport)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::terra_perceive::_LatencyMetrics_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::terra_perceive::_SessionReport_default_instance_),
};

const char descriptor_table_protodef_telemetry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017telemetry.proto\022\016terra_perceive\"\211\001\n\016La"
  "tencyMetrics\022\021\n\ttimestamp\030\001 \001(\001\022\016\n\006modul"
  "e\030\002 \001(\t\022\016\n\006p50_ms\030\003 \001(\002\022\016\n\006p95_ms\030\004 \001(\002\022"
  "\016\n\006p99_ms\030\005 \001(\002\022\021\n\tdrop_rate\030\006 \001(\002\022\021\n\thz"
  "_actual\030\007 \001(\002\"\206\002\n\rSessionReport\022\022\n\nstart"
  "_time\030\001 \001(\001\022\020\n\010end_time\030\002 \001(\001\022\024\n\014total_f"
  "rames\030\003 \001(\r\022\030\n\020total_detections\030\004 \001(\r\022\032\n"
  "\022total_safety_stops\030\005 \001(\r\022\032\n\022total_safet"
  "y_slows\030\006 \001(\r\022\026\n\016uptime_percent\030\007 \001(\002\022\027\n"
  "\017area_covered_m2\030\010 \001(\002\0226\n\016module_metrics"
  "\030\t \003(\0132\036.terra_perceive.LatencyMetricsb\006"
  "proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_telemetry_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_telemetry_2eproto_sccs[2] = {
  &scc_info_LatencyMetrics_telemetry_2eproto.base,
  &scc_info_SessionReport_telemetry_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_telemetry_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto = {
  false, false, descriptor_table_protodef_telemetry_2eproto, "telemetry.proto", 446,
  &descriptor_table_telemetry_2eproto_once, descriptor_table_telemetry_2eproto_sccs, descriptor_table_telemetry_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_telemetry_2eproto::offsets,
  file_level_metadata_telemetry_2eproto, 2, file_level_enum_descriptors_telemetry_2eproto, file_level_service_descriptors_telemetry_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_telemetry_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_telemetry_2eproto)), true);
namespace terra_perceive {

// ===================================================================

void LatencyMetrics::InitAsDefaultInstance() {
}
class LatencyMetrics::_Internal {
 public:
};

LatencyMetrics::LatencyMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:terra_perceive.LatencyMetrics)
}
LatencyMetrics::LatencyMetrics(const LatencyMetrics& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  module_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_module().empty()) {
    module_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_module(),
      GetArena());
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&hz_actual_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(hz_actual_));
  // @@protoc_insertion_point(copy_constructor:terra_perceive.LatencyMetrics)
}

void LatencyMetrics::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LatencyMetrics_telemetry_2eproto.base);
  module_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hz_actual_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(hz_actual_));
}

LatencyMetrics::~LatencyMetrics() {
  // @@protoc_insertion_point(destructor:terra_perceive.LatencyMetrics)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LatencyMetrics::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  module_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LatencyMetrics::ArenaDtor(void* object) {
  LatencyMetrics* _this = reinterpret_cast< LatencyMetrics* >(object);
  (void)_this;
}
void LatencyMetrics::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LatencyMetrics::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LatencyMetrics& LatencyMetrics::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LatencyMetrics_telemetry_2eproto.base);
  return *internal_default_instance();
}


void LatencyMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:terra_perceive.LatencyMetrics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  module_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hz_actual_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(hz_actual_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LatencyMetrics::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string module = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_module();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "terra_perceive.LatencyMetrics.module"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float p50_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          p50_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float p95_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          p95_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float p99_ms = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          p99_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float drop_rate = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          drop_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float hz_actual = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          hz_actual_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LatencyMetrics::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terra_perceive.LatencyMetrics)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_timestamp(), target);
  }

  // string module = 2;
  if (this->module().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_module().data(), static_cast<int>(this->_internal_module().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "terra_perceive.LatencyMetrics.module");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_module(), target);
  }

  // float p50_ms = 3;
  if (!(this->p50_ms() <= 0 && this->p50_ms() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_p50_ms(), target);
  }

  // float p95_ms = 4;
  if (!(this->p95_ms() <= 0 && this->p95_ms() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_p95_ms(), target);
  }

  // float p99_ms = 5;
  if (!(this->p99_ms() <= 0 && this->p99_ms() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_p99_ms(), target);
  }

  // float drop_rate = 6;
  if (!(this->drop_rate() <= 0 && this->drop_rate() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_drop_rate(), target);
  }

  // float hz_actual = 7;
  if (!(this->hz_actual() <= 0 && this->hz_actual() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_hz_actual(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terra_perceive.LatencyMetrics)
  return target;
}

size_t LatencyMetrics::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terra_perceive.LatencyMetrics)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string module = 2;
  if (this->module().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_module());
  }

  // double timestamp = 1;
  if (!(this->timestamp() <= 0 && this->timestamp() >= 0)) {
    total_size += 1 + 8;
  }

  // float p50_ms = 3;
  if (!(this->p50_ms() <= 0 && this->p50_ms() >= 0)) {
    total_size += 1 + 4;
  }

  // float p95_ms = 4;
  if (!(this->p95_ms() <= 0 && this->p95_ms() >= 0)) {
    total_size += 1 + 4;
  }

  // float p99_ms = 5;
  if (!(this->p99_ms() <= 0 && this->p99_ms() >= 0)) {
    total_size += 1 + 4;
  }

  // float drop_rate = 6;
  if (!(this->drop_rate() <= 0 && this->drop_rate() >= 0)) {
    total_size += 1 + 4;
  }

  // float hz_actual = 7;
  if (!(this->hz_actual() <= 0 && this->hz_actual() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LatencyMetrics::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:terra_perceive.LatencyMetrics)
  GOOGLE_DCHECK_NE(&from, this);
  const LatencyMetrics* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LatencyMetrics>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:terra_perceive.LatencyMetrics)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:terra_perceive.LatencyMetrics)
    MergeFrom(*source);
  }
}

void LatencyMetrics::MergeFrom(const LatencyMetrics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:terra_perceive.LatencyMetrics)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.module().size() > 0) {
    _internal_set_module(from._internal_module());
  }
  if (!(from.timestamp() <= 0 && from.timestamp() >= 0)) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  if (!(from.p50_ms() <= 0 && from.p50_ms() >= 0)) {
    _internal_set_p50_ms(from._internal_p50_ms());
  }
  if (!(from.p95_ms() <= 0 && from.p95_ms() >= 0)) {
    _internal_set_p95_ms(from._internal_p95_ms());
  }
  if (!(from.p99_ms() <= 0 && from.p99_ms() >= 0)) {
    _internal_set_p99_ms(from._internal_p99_ms());
  }
  if (!(from.drop_rate() <= 0 && from.drop_rate() >= 0)) {
    _internal_set_drop_rate(from._internal_drop_rate());
  }
  if (!(from.hz_actual() <= 0 && from.hz_actual() >= 0)) {
    _internal_set_hz_actual(from._internal_hz_actual());
  }
}

void LatencyMetrics::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:terra_perceive.LatencyMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LatencyMetrics::CopyFrom(const LatencyMetrics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terra_perceive.LatencyMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LatencyMetrics::IsInitialized() const {
  return true;
}

void LatencyMetrics::InternalSwap(LatencyMetrics* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  module_.Swap(&other->module_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LatencyMetrics, hz_actual_)
      + sizeof(LatencyMetrics::hz_actual_)
      - PROTOBUF_FIELD_OFFSET(LatencyMetrics, timestamp_)>(
          reinterpret_cast<char*>(&timestamp_),
          reinterpret_cast<char*>(&other->timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LatencyMetrics::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SessionReport::InitAsDefaultInstance() {
}
class SessionReport::_Internal {
 public:
};

SessionReport::SessionReport(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  module_metrics_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:terra_perceive.SessionReport)
}
SessionReport::SessionReport(const SessionReport& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      module_metrics_(from.module_metrics_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&start_time_, &from.start_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&area_covered_m2_) -
    reinterpret_cast<char*>(&start_time_)) + sizeof(area_covered_m2_));
  // @@protoc_insertion_point(copy_constructor:terra_perceive.SessionReport)
}

void SessionReport::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SessionReport_telemetry_2eproto.base);
  ::memset(&start_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&area_covered_m2_) -
      reinterpret_cast<char*>(&start_time_)) + sizeof(area_covered_m2_));
}

SessionReport::~SessionReport() {
  // @@protoc_insertion_point(destructor:terra_perceive.SessionReport)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SessionReport::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SessionReport::ArenaDtor(void* object) {
  SessionReport* _this = reinterpret_cast< SessionReport* >(object);
  (void)_this;
}
void SessionReport::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SessionReport::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SessionReport& SessionReport::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SessionReport_telemetry_2eproto.base);
  return *internal_default_instance();
}


void SessionReport::Clear() {
// @@protoc_insertion_point(message_clear_start:terra_perceive.SessionReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  module_metrics_.Clear();
  ::memset(&start_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&area_covered_m2_) -
      reinterpret_cast<char*>(&start_time_)) + sizeof(area_covered_m2_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SessionReport::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double start_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          start_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double end_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          end_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // uint32 total_frames = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          total_frames_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 total_detections = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          total_detections_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 total_safety_stops = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          total_safety_stops_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 total_safety_slows = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          total_safety_slows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float uptime_percent = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          uptime_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float area_covered_m2 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          area_covered_m2_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated .terra_perceive.LatencyMetrics module_metrics = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_module_metrics(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SessionReport::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terra_perceive.SessionReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double start_time = 1;
  if (!(this->start_time() <= 0 && this->start_time() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_start_time(), target);
  }

  // double end_time = 2;
  if (!(this->end_time() <= 0 && this->end_time() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_end_time(), target);
  }

  // uint32 total_frames = 3;
  if (this->total_frames() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_total_frames(), target);
  }

  // uint32 total_detections = 4;
  if (this->total_detections() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_total_detections(), target);
  }

  // uint32 total_safety_stops = 5;
  if (this->total_safety_stops() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_total_safety_stops(), target);
  }

  // uint32 total_safety_slows = 6;
  if (this->total_safety_slows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_total_safety_slows(), target);
  }

  // float uptime_percent = 7;
  if (!(this->uptime_percent() <= 0 && this->uptime_percent() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_uptime_percent(), target);
  }

  // float area_covered_m2 = 8;
  if (!(this->area_covered_m2() <= 0 && this->area_covered_m2() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_area_covered_m2(), target);
  }

  // repeated .terra_perceive.LatencyMetrics module_metrics = 9;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_module_metrics_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, this->_internal_module_metrics(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terra_perceive.SessionReport)
  return target;
}

size_t SessionReport::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terra_perceive.SessionReport)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .terra_perceive.LatencyMetrics module_metrics = 9;
  total_size += 1UL * this->_internal_module_metrics_size();
  for (const auto& msg : this->module_metrics_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // double start_time = 1;
  if (!(this->start_time() <= 0 && this->start_time() >= 0)) {
    total_size += 1 + 8;
  }

  // double end_time = 2;
  if (!(this->end_time() <= 0 && this->end_time() >= 0)) {
    total_size += 1 + 8;
  }

  // uint32 total_frames = 3;
  if (this->total_frames() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_total_frames());
  }

  // uint32 total_detections = 4;
  if (this->total_detections() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_total_detections());
  }

  // uint32 total_safety_stops = 5;
  if (this->total_safety_stops() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_total_safety_stops());
  }

  // uint32 total_safety_slows = 6;
  if (this->total_safety_slows() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_total_safety_slows());
  }

  // float uptime_percent = 7;
  if (!(this->uptime_percent() <= 0 && this->uptime_percent() >= 0)) {
    total_size += 1 + 4;
  }

  // float area_covered_m2 = 8;
  if (!(this->area_covered_m2() <= 0 && this->area_covered_m2() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SessionReport::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:terra_perceive.SessionReport)
  GOOGLE_DCHECK_NE(&from, this);
  const SessionReport* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SessionReport>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:terra_perceive.SessionReport)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:terra_perceive.SessionReport)
    MergeFrom(*source);
  }
}

void SessionReport::MergeFrom(const SessionReport& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:terra_perceive.SessionReport)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  module_metrics_.MergeFrom(from.module_metrics_);
  if (!(from.start_time() <= 0 && from.start_time() >= 0)) {
    _internal_set_start_time(from._internal_start_time());
  }
  if (!(from.end_time() <= 0 && from.end_time() >= 0)) {
    _internal_set_end_time(from._internal_end_time());
  }
  if (from.total_frames() != 0) {
    _internal_set_total_frames(from._internal_total_frames());
  }
  if (from.total_detections() != 0) {
    _internal_set_total_detections(from._internal_total_detections());
  }
  if (from.total_safety_stops() != 0) {
    _internal_set_total_safety_stops(from._internal_total_safety_stops());
  }
  if (from.total_safety_slows() != 0) {
    _internal_set_total_safety_slows(from._internal_total_safety_slows());
  }
  if (!(from.uptime_percent() <= 0 && from.uptime_percent() >= 0)) {
    _internal_set_uptime_percent(from._internal_uptime_percent());
  }
  if (!(from.area_covered_m2() <= 0 && from.area_covered_m2() >= 0)) {
    _internal_set_area_covered_m2(from._internal_area_covered_m2());
  }
}

void SessionReport::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:terra_perceive.SessionReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SessionReport::CopyFrom(const SessionReport& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terra_perceive.SessionReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionReport::IsInitialized() const {
  return true;
}

void SessionReport::InternalSwap(SessionReport* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  module_metrics_.InternalSwap(&other->module_metrics_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SessionReport, area_covered_m2_)
      + sizeof(SessionReport::area_covered_m2_)
      - PROTOBUF_FIELD_OFFSET(SessionReport, start_time_)>(
          reinterpret_cast<char*>(&start_time_),
          reinterpret_cast<char*>(&other->start_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SessionReport::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace terra_perceive
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::terra_perceive::LatencyMetrics* Arena::CreateMaybeMessage< ::terra_perceive::LatencyMetrics >(Arena* arena) {
  return Arena::CreateMessageInternal< ::terra_perceive::LatencyMetrics >(arena);
}
template<> PROTOBUF_NOINLINE ::terra_perceive::SessionReport* Arena::CreateMaybeMessage< ::terra_perceive::SessionReport >(Arena* arena) {
  return Arena::CreateMessageInternal< ::terra_perceive::SessionReport >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
