# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0eterra_perceive\"\x89\x01\n\x0eLatencyMetrics\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06module\x18\x02 \x01(\t\x12\x0e\n\x06p50_ms\x18\x03 \x01(\x02\x12\x0e\n\x06p95_ms\x18\x04 \x01(\x02\x12\x0e\n\x06p99_ms\x18\x05 \x01(\x02\x12\x11\n\tdrop_rate\x18\x06 \x01(\x02\x12\x11\n\thz_actual\x18\x07 \x01(\x02\"\x86\x02\n\rSessionReport\x12\x12\n\nstart_time\x18\x01 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_frames\x18\x03 \x01(\r\x12\x18\n\x10total_detections\x18\x04 \x01(\r\x12\x1a\n\x12total_safety_stops\x18\x05 \x01(\r\x12\x1a\n\x12total_safety_slows\x18\x06 \x01(\r\x12\x16\n\x0euptime_percent\x18\x07 \x01(\x02\x12\x17\n\x0f\x61rea_covered_m2\x18\x08 \x01(\x02\x12\x36\n\x0emodule_metrics\x18\t \x03(\x0b\x32\x1e.terra_perceive.LatencyMetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LATENCYMETRICS']._serialized_start=36
  _globals['_LATENCYMETRICS']._serialized_end=173
  _globals['_SESSIONREPORT']._serialized_start=176
  _globals['_SESSIONREPORT']._serialized_end=438
# @@protoc_insertion_point(module_scope)
