#!/usr/bin/env python3
"""torch_to_eigen_check.py — export the trained encoder for C++ inference.

Reads the PyTorch checkpoint produced by `train.py` and produces three
artifacts that wire the trained encoder into the C++ side:

    1. include/appearance_model_weights.hpp — overwrites the placeholder
       weights with real trained values. After this lands, the C++
       AppearanceEncoder constructor copies these into Eigen matrices,
       and AppearanceEncoder::encode() produces real embeddings instead
       of zero vectors.

    2. tests/data/appearance_reference.csv — 5 (input, expected_embedding)
       pairs. Each row: f0..f7, e0..e31 (8 + 32 = 40 floats). Drives the
       gtest `EncoderMatchesPyTorchReference` (currently SKIPPED). When
       the test passes with < 1e-5 max abs diff, we have proof that the
       Python reference and the C++ Eigen forward pass agree
       byte-equivalently.

    3. tests/data/appearance_triplets.csv — 100 anchor/positive/negative
       triplets. Each row: 24 floats (a, p, n × 8 features each). Drives
       the gtest `EmbeddingDistanceMonotoneOnAugmentation`. Asserts that
       on ≥ 95% of triplets, d(anchor, positive_aug) < d(anchor, negative).

After running this script:
    - colcon rebuild → AppearanceEncoder picks up real weights.
    - Remove GTEST_SKIP from the two gated tests in test_appearance_encoder.cpp.
    - Build + run: ./build/construction_perception/test_appearance_encoder
      → 4/4 should pass.

Usage:
    python python/appearance/torch_to_eigen_check.py \\
        --checkpoint     python/appearance/checkpoints/encoder.pt \\
        --clusters-dir   /media/.../clusters_sweetspot \\
        --header-out     include/appearance_model_weights.hpp \\
        --reference-csv  tests/data/appearance_reference.csv \\
        --triplets-csv   tests/data/appearance_triplets.csv

The script also runs an end-to-end self-check:
    - Runs the PyTorch encoder on the 5 reference inputs.
    - Manually runs the same forward pass using ONLY the constexpr arrays
      we just dumped, applied via numpy ops (mimicking what Eigen does
      element-wise on the C++ side).
    - Reports the max abs diff. If > 1e-6 between PyTorch and the
      manually-replayed-from-header forward pass, something's wrong with
      the export.
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn.functional as F

# Reuse training-time pieces so the export pipeline runs the SAME forward
# pass that was trained.
sys.path.insert(0, str(Path(__file__).parent))
from train import AppearanceMLP, Augmenter                     # noqa: E402
from extract_features import cluster_features, load_cluster_csv  # noqa: E402


# =============================================================================
# Header generation. Format must EXACTLY match the placeholder in
# include/appearance_model_weights.hpp so the C++ constructor's array
# indexing (kW1[r * 8 + c]) keeps working.
# =============================================================================

HEADER_TEMPLATE = """\
// appearance_model_weights.hpp — AUTO-GENERATED by python/appearance/torch_to_eigen_check.py
//
// Source checkpoint: {ckpt_path}
// Best val accuracy: {best_val_accuracy:.4f}
// Generated:         {timestamp}
//
// Layout matches src/appearance_encoder.cpp::AppearanceEncoder():
//     kW1[out * 8  + in]   for layer 1  (8 → 64)
//     kW2[out * 64 + in]   for layer 2  (64 → 32)
//     kW3[out * 32 + in]   for layer 3  (32 → 32)
//     kFeatMean / kFeatStd : per-feature z-score statistics, applied
//                            in encoder Step 1 BEFORE the linear layers.
//
// Do not edit by hand — re-run torch_to_eigen_check.py to refresh.

#pragma once

namespace tracker {{
namespace appearance_weights {{

constexpr float kFeatMean[8] = {{
{feat_mean}
}};

constexpr float kFeatStd[8] = {{
{feat_std}
}};

constexpr float kW1[64 * 8] = {{
{w1}
}};
constexpr float kB1[64] = {{
{b1}
}};

constexpr float kW2[32 * 64] = {{
{w2}
}};
constexpr float kB2[32] = {{
{b2}
}};

constexpr float kW3[32 * 32] = {{
{w3}
}};
constexpr float kB3[32] = {{
{b3}
}};

}}  // namespace appearance_weights
}}  // namespace tracker
"""


def fmt_array(arr: np.ndarray, line_width: int = 8) -> str:
    """Format a flat float array as comma-separated `Xf` literals,
    `line_width` per line, indented 4 spaces. Matches the visual format
    of the placeholder header for clean diffs."""
    flat = arr.ravel()
    lines = []
    for i in range(0, flat.size, line_width):
        chunk = flat[i:i + line_width]
        lines.append("    " + ", ".join(f"{x:.9g}f" for x in chunk) + ",")
    # Strip trailing comma on the last entry — C++ tolerates it but
    # cleaner without.
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def export_header(model: AppearanceMLP, ckpt_meta: dict, out_path: Path) -> None:
    """Dump trained MLP weights into a constexpr-only C++ header that
    matches the placeholder layout exactly.
    """
    sd = model.state_dict()

    # Z-score stats (encoder Step 1).
    feat_mean = model.feat_mean.detach().cpu().numpy()
    feat_std  = model.feat_std.detach().cpu().numpy()

    # Layer weights — PyTorch stores Linear(out, in) as `weight: (out, in)`,
    # which is row-major when flattened. Same as our kW[out*in_cols + in]
    # convention. `.contiguous()` guarantees the memory layout.
    W1 = sd["l1.weight"].detach().cpu().contiguous().numpy()
    b1 = sd["l1.bias"  ].detach().cpu().contiguous().numpy()
    W2 = sd["l2.weight"].detach().cpu().contiguous().numpy()
    b2 = sd["l2.bias"  ].detach().cpu().contiguous().numpy()
    W3 = sd["l3.weight"].detach().cpu().contiguous().numpy()
    b3 = sd["l3.bias"  ].detach().cpu().contiguous().numpy()

    # Shape sanity. Catches a misconfigured architecture (rare but cheap).
    assert W1.shape == (64,  8),  W1.shape
    assert W2.shape == (32, 64),  W2.shape
    assert W3.shape == (32, 32),  W3.shape
    assert b1.shape == (64,)
    assert b2.shape == (32,)
    assert b3.shape == (32,)

    import datetime
    text = HEADER_TEMPLATE.format(
        ckpt_path=str(ckpt_meta["path"]),
        best_val_accuracy=ckpt_meta.get("val_accuracy", float("nan")),
        timestamp=datetime.datetime.now().isoformat(timespec="seconds"),
        feat_mean=fmt_array(feat_mean),
        feat_std =fmt_array(feat_std),
        w1=fmt_array(W1), b1=fmt_array(b1),
        w2=fmt_array(W2), b2=fmt_array(b2),
        w3=fmt_array(W3), b3=fmt_array(b3),
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text)
    print(f"[export] wrote header → {out_path}")


# =============================================================================
# Reference CSV — proves the C++ forward pass matches PyTorch.
# =============================================================================

def numpy_forward_from_state_dict(features: np.ndarray, sd: dict,
                                  feat_mean: np.ndarray, feat_std: np.ndarray
                                  ) -> np.ndarray:
    """Replay the encoder forward pass using ONLY numpy ops on the same
    weights the header dumps. Lets us self-check that the dumped numbers
    really do reproduce the trained encoder bit-for-bit.
    """
    x = (features - feat_mean) / feat_std

    W1 = sd["l1.weight"].cpu().numpy(); b1 = sd["l1.bias"].cpu().numpy()
    W2 = sd["l2.weight"].cpu().numpy(); b2 = sd["l2.bias"].cpu().numpy()
    W3 = sd["l3.weight"].cpu().numpy(); b3 = sd["l3.bias"].cpu().numpy()

    h = np.maximum(W1 @ x.T + b1[:, None], 0.0)            # (64, B)
    h = np.maximum(W2 @ h   + b2[:, None], 0.0)            # (32, B)
    h = (W3 @ h + b3[:, None]).T                           # (B, 32)
    n = np.linalg.norm(h, axis=1, keepdims=True)
    n = np.where(n > 1e-12, n, 1.0)
    return h / n


def export_reference_csv(model: AppearanceMLP, out_path: Path,
                         seed: int = 0) -> None:
    """5 random feature vectors → encoded embeddings (40 floats per row)."""
    model.eval()
    rng = np.random.default_rng(seed)
    # Sample inputs from a unit normal — covers a generic feature space.
    # 5 rows is the count the gtest expects.
    feats = rng.standard_normal((5, 8)).astype(np.float32)
    with torch.no_grad():
        x = torch.tensor(feats)
        emb = model(x).numpy()                             # (5, 32)

    # Self-check: numpy replay of the same forward pass must match the
    # PyTorch model output to machine precision. If this fails the export
    # is broken — the C++ side won't agree either.
    sd = model.state_dict()
    fm = model.feat_mean.detach().cpu().numpy()
    fs = model.feat_std.detach().cpu().numpy()
    emb_replay = numpy_forward_from_state_dict(feats, sd, fm, fs)
    diff = float(np.abs(emb - emb_replay).max())
    if diff > 1e-6:
        print(f"[export] WARN: numpy replay diverges from torch by {diff:.2e}",
              file=sys.stderr)
    else:
        print(f"[export] numpy↔torch self-check OK (max abs diff {diff:.2e})")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        w = csv.writer(f)
        header = [f"f{i}" for i in range(8)] + [f"e{i}" for i in range(32)]
        w.writerow(header)
        for row_feat, row_emb in zip(feats, emb):
            w.writerow([f"{v:.9g}" for v in row_feat]
                       + [f"{v:.9g}" for v in row_emb])
    print(f"[export] wrote reference → {out_path}")


# =============================================================================
# Triplets CSV — drives EmbeddingDistanceMonotoneOnAugmentation.
# =============================================================================

def export_triplets_csv(out_path: Path,
                        clusters_dir: Path,
                        n_triplets: int,
                        seed: int = 0) -> None:
    """Sample n_triplets (anchor, jittered_anchor, random_other) feature
    triples from the cluster set. Pure feature triples — no embeddings.
    The gtest computes embeddings via the trained encoder.

    Each row: a0..a7, p0..p7, n0..n7 (24 floats).
    """
    rng_np = np.random.default_rng(seed)
    rng_py = random.Random(seed)
    aug = Augmenter(rng=rng_np)

    # Load enough clusters to sample from. Skip very small clusters
    # (geometric features are unstable on N<5).
    cluster_files = sorted(clusters_dir.glob("clusters_*.csv"))
    rng_py.shuffle(cluster_files)
    bank: List[np.ndarray] = []
    for cf in cluster_files:
        if len(bank) >= 2 * n_triplets + 100:               # enough headroom
            break
        for cid, pts in load_cluster_csv(cf).items():
            if pts.shape[0] >= 5:
                bank.append(pts)
    if len(bank) < n_triplets + 1:
        raise SystemExit(f"need ≥ {n_triplets + 1} clusters with ≥ 5 points; "
                         f"got {len(bank)}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [f"a{i}" for i in range(8)] +
            [f"p{i}" for i in range(8)] +
            [f"n{i}" for i in range(8)]
        )
        for _ in range(n_triplets):
            anchor_pts = rng_py.choice(bank)
            negative_pts = rng_py.choice(bank)
            # If unlucky enough to draw the same cluster, redraw once.
            if negative_pts is anchor_pts:
                negative_pts = rng_py.choice(bank)

            anchor_feat   = cluster_features(anchor_pts)
            positive_feat = cluster_features(aug(anchor_pts))
            negative_feat = cluster_features(negative_pts)
            w.writerow(
                [f"{v:.9g}" for v in anchor_feat] +
                [f"{v:.9g}" for v in positive_feat] +
                [f"{v:.9g}" for v in negative_feat]
            )
    print(f"[export] wrote triplets → {out_path}  ({n_triplets} rows)")


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    p = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                description=__doc__)
    p.add_argument("--checkpoint",    type=Path, required=True,
                   help="encoder.pt from train.py (best-val checkpoint)")
    p.add_argument("--clusters-dir",  type=Path, required=True,
                   help="dir with clusters_NNNNNN.csv (for triplet sampling)")
    p.add_argument("--header-out",    type=Path,
                   default=Path("include/appearance_model_weights.hpp"))
    p.add_argument("--reference-csv", type=Path,
                   default=Path("tests/data/appearance_reference.csv"))
    p.add_argument("--triplets-csv",  type=Path,
                   default=Path("tests/data/appearance_triplets.csv"))
    p.add_argument("--n-triplets",    type=int, default=100)
    p.add_argument("--seed",          type=int, default=0)
    args = p.parse_args()

    # Load checkpoint. Whatever device the checkpoint was saved on, we
    # re-build the model on CPU here — the export is pure numpy IO.
    print(f"[export] loading {args.checkpoint}")
    ck = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    feat_mean = np.asarray(ck["feat_mean"], dtype=np.float32)
    feat_std  = np.asarray(ck["feat_std"],  dtype=np.float32)
    model = AppearanceMLP(feat_mean, feat_std)
    model.load_state_dict(ck["state_dict"])
    model.eval()
    print(f"[export] best-val checkpoint: epoch {ck.get('epoch', '?')}, "
          f"val_acc {ck.get('val_accuracy', float('nan')):.4f}, "
          f"τ {ck.get('val_threshold', float('nan')):.3f}")

    ckpt_meta = {"path": args.checkpoint,
                 "val_accuracy": ck.get("val_accuracy", float("nan"))}

    # 1) header (overwrites the placeholder)
    export_header(model, ckpt_meta, args.header_out)

    # 2) reference CSV (drives EncoderMatchesPyTorchReference)
    export_reference_csv(model, args.reference_csv, seed=args.seed)

    # 3) triplets CSV (drives EmbeddingDistanceMonotoneOnAugmentation)
    export_triplets_csv(args.triplets_csv, args.clusters_dir,
                        args.n_triplets, seed=args.seed)

    print()
    print("[export] DONE.")
    print("[export] next steps on the C++ side:")
    print("  colcon build --packages-select construction_perception")
    print("  # remove GTEST_SKIP from the two gated tests in")
    print("  # tests/cpp/test_appearance_encoder.cpp")
    print("  ./build/construction_perception/test_appearance_encoder")


if __name__ == "__main__":
    main()
