"""
detection_node.py — YOLOv8n COCO-class object detection (P2-M5.A1).

Two source modes:
  --source live      Subscribe to NATS subject ``sensor.camera.rgb`` (CameraFrame
                     protobuf with JPEG bytes). Used in the M3-style live demo
                     alongside ``scripts/publish_camera_stream.py``.
  --source replay    Walk a directory of jpgs in lexical order, paced at --hz.
                     Used by tracker_runner / offline ablations.

In both modes the node:
  1. Decodes the image (cv2).
  2. Runs YOLOv8n inference at conf >= 0.25 (loose scan threshold).
  3. Filters to the M5 target classes (person/bicycle/car/motorcycle/truck) at
     conf >= 0.5.
  4. Builds a DetectionList protobuf (perception.proto) with one Detection2D
     per kept detection.
  5. Publishes the serialized DetectionList on ``perception.objects.detections``.
  6. Optionally appends one NDJSON line per frame to --out-ndjson for offline
     tracker replay (matches the m4_perframe NDJSON convention).

Boundary clarification (debug log 2026-05-01):
  ``Detection2D.depth_3d`` is left as 0 here. Depth fill-in is the job of the
  tracker node (A2) which holds the LiDAR + calibration. Detection alone can't
  produce 3D without LiDAR.

Mentor-mode tag: pure glue. No algorithmic content the user is expected to fill in.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import re
import sys
import time
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

# Local imports — the protobuf bindings are generated by transport/generate_protos.sh.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from transport.nats_adapter import Adapter  # noqa: E402
from transport.proto import perception_pb2  # noqa: E402

log = logging.getLogger("detection_node")

TARGET_CLASSES = {0: "person", 1: "bicycle", 2: "car", 3: "motorcycle", 7: "truck"}
SCAN_CONF = 0.25      # loose threshold passed to YOLO; we filter again at HEADLINE_CONF
HEADLINE_CONF = 0.5   # what counts as a real detection

DEFAULT_SUBJECT_OUT = "perception.objects.detections"
DEFAULT_SUBJECT_IN_LIVE = "sensor.camera.rgb"
DEFAULT_WEIGHTS = "/media/nishant/SeeGayt2/terra_perceive/models/yolov8n.pt"
DEFAULT_NDJSON = "/media/nishant/SeeGayt2/terra_perceive/m5_phaseA/detection_replay.ndjson"

FRAME_IDX_RE = re.compile(r"frame(\d+)")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--source", choices=("live", "replay"), default="replay")
    p.add_argument(
        "--frames-dir",
        default="data/RELLIS-3D/Rellis_3D_pylon_camera_node/Rellis-3D/00000/pylon_camera_node",
        help="Directory of jpgs for --source replay.",
    )
    p.add_argument("--hz", type=float, default=5.0, help="Replay rate in Hz.")
    p.add_argument("--start-frame", type=int, default=0)
    p.add_argument("--end-frame", type=int, default=None, help="Exclusive; default whole dir.")
    p.add_argument("--nats-url", default="nats://localhost:4222")
    p.add_argument("--subject-in", default=DEFAULT_SUBJECT_IN_LIVE)
    p.add_argument("--subject-out", default=DEFAULT_SUBJECT_OUT)
    p.add_argument("--weights", default=DEFAULT_WEIGHTS)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--device", default="cpu")
    p.add_argument(
        "--out-ndjson", default=DEFAULT_NDJSON,
        help="Append-only file: one JSON line per frame. Use empty string to disable.",
    )
    p.add_argument(
        "--no-publish", action="store_true",
        help="Skip NATS publish (useful for smoke-testing the YOLO + NDJSON path).",
    )
    p.add_argument("--max-frames", type=int, default=None)
    return p.parse_args()


def frame_id_from_name(name: str, fallback: int) -> str:
    m = FRAME_IDX_RE.search(name)
    if m:
        return f"frame_{int(m.group(1)):06d}"
    return f"frame_{fallback:06d}"


def build_detection_list(
    img: np.ndarray, model, frame_id: str, source_tag: str,
) -> tuple[perception_pb2.DetectionList, list[dict]]:
    """Run YOLO and pack DetectionList. Returns (proto_msg, ndjson_dets)."""
    result = model.predict(img, conf=SCAN_CONF, imgsz=640, device="cpu", verbose=False)[0]
    msg = perception_pb2.DetectionList()
    msg.header.timestamp = time.time()
    msg.header.frame_id = frame_id
    msg.header.schema_version = 1
    msg.header.source = source_tag

    ndjson_dets: list[dict] = []
    if result.boxes is not None and result.boxes.shape[0] > 0:
        cls_ids = result.boxes.cls.cpu().numpy().astype(int)
        confs = result.boxes.conf.cpu().numpy()
        xyxy = result.boxes.xyxy.cpu().numpy()
        for cid, cf, box in zip(cls_ids, confs, xyxy):
            if cid not in TARGET_CLASSES or cf < HEADLINE_CONF:
                continue
            d = msg.detections.add()
            d.x_min, d.y_min, d.x_max, d.y_max = (
                float(box[0]), float(box[1]), float(box[2]), float(box[3]),
            )
            d.class_id = int(cid)
            d.confidence = float(cf)
            d.depth_3d = 0.0  # filled by tracker_node A2 via CamLidarProjector
            ndjson_dets.append(
                {
                    "class_id": int(cid),
                    "class_name": TARGET_CLASSES[int(cid)],
                    "conf": float(cf),
                    "x1": float(box[0]), "y1": float(box[1]),
                    "x2": float(box[2]), "y2": float(box[3]),
                },
            )
    return msg, ndjson_dets


async def run_replay(args: argparse.Namespace) -> int:
    from ultralytics import YOLO  # local import keeps `--help` snappy

    frames = sorted(Path(args.frames_dir).resolve().glob("frame*.jpg"))
    if not frames:
        log.error("no frames in %s", args.frames_dir)
        return 1
    end = args.end_frame if args.end_frame is not None else len(frames)
    frames = frames[args.start_frame:end]
    if args.max_frames is not None:
        frames = frames[: args.max_frames]
    log.info("replay: %d frames at %.1f Hz from %s", len(frames), args.hz, args.frames_dir)

    Path(args.weights).parent.mkdir(parents=True, exist_ok=True)
    model = YOLO(args.weights)

    adapter: Optional[Adapter] = None
    if not args.no_publish:
        adapter = Adapter(args.nats_url)
        await adapter.connect()

    ndjson_path: Optional[Path] = None
    if args.out_ndjson:
        ndjson_path = Path(args.out_ndjson)
        ndjson_path.parent.mkdir(parents=True, exist_ok=True)
        # Truncate at start of run; honest replay must not bleed across runs.
        ndjson_path.write_text("")

    period = 1.0 / max(args.hz, 1e-3)
    started = time.time()
    n_pub = 0
    n_dets_total = 0
    for k, fp in enumerate(frames):
        loop_t0 = time.time()
        img = cv2.imread(str(fp))
        if img is None:
            log.warning("skip unreadable %s", fp)
            continue
        frame_id = frame_id_from_name(fp.name, args.start_frame + k)
        msg, ndjson_dets = build_detection_list(
            img, model, frame_id, source_tag="detection_node:replay",
        )
        n_dets_total += len(ndjson_dets)
        if adapter is not None:
            await adapter.publish(args.subject_out, msg.SerializeToString())
            n_pub += 1
        if ndjson_path is not None:
            with ndjson_path.open("a") as fh:
                fh.write(
                    json.dumps(
                        {
                            "frame_id": frame_id,
                            "timestamp": msg.header.timestamp,
                            "n_detections": len(ndjson_dets),
                            "detections": ndjson_dets,
                        },
                    )
                    + "\n",
                )
        elapsed = time.time() - loop_t0
        if elapsed < period:
            await asyncio.sleep(period - elapsed)

    wall = time.time() - started
    log.info(
        "replay done: frames=%d  pub=%d  total_dets=%d  wall=%.1fs  fps=%.2f",
        len(frames), n_pub, n_dets_total, wall, len(frames) / max(wall, 1e-3),
    )
    if adapter is not None:
        await adapter.close()
    return 0


async def run_live(args: argparse.Namespace) -> int:
    from ultralytics import YOLO

    Path(args.weights).parent.mkdir(parents=True, exist_ok=True)
    model = YOLO(args.weights)

    sub = Adapter(args.nats_url)
    pub = Adapter(args.nats_url)
    await sub.connect()
    await pub.connect()

    state = {"n": 0}

    async def handler(payload: bytes) -> None:
        cam = perception_pb2.CameraFrame()
        cam.ParseFromString(payload)
        if cam.encoding not in ("jpeg", "jpg", "png"):
            log.warning("unsupported encoding=%r; skip", cam.encoding)
            return
        arr = np.frombuffer(cam.data, dtype=np.uint8)
        img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        if img is None:
            log.warning("imdecode failed; skip")
            return
        frame_id = cam.header.frame_id or f"frame_{state['n']:06d}"
        msg, _ = build_detection_list(
            img, model, frame_id, source_tag="detection_node:live",
        )
        await pub.publish(args.subject_out, msg.SerializeToString())
        state["n"] += 1

    await sub.subscribe(args.subject_in, handler)
    log.info("live: subscribed=%s  publishing=%s", args.subject_in, args.subject_out)
    try:
        while True:
            await asyncio.sleep(1.0)
    except asyncio.CancelledError:
        pass
    finally:
        await sub.close()
        await pub.close()
    return 0


def main() -> int:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s  %(levelname)s  %(name)s  %(message)s",
    )
    args = parse_args()
    if args.source == "replay":
        return asyncio.run(run_replay(args))
    return asyncio.run(run_live(args))


if __name__ == "__main__":
    sys.exit(main())
