#!/usr/bin/env bash
# render_blog_animations.sh — render the three closing-hero animations
# for the M10 / M12 / M13.5 blog posts. Each config produces its own
# tracks.csv (running the tracker_runner with the matching params),
# then the side-by-side DBSCAN vs SORT animation is rendered to a
# unique MP4 + GIF.
#
# Four configs (chronological progression of the blog story):
#
#   1. m4_pretune   — Script-default M4 BEFORE the post-M10 tuning.
#                     CV filter, min_hits=1, process_noise=2.0,
#                     max_misses=10. Result: 1678 distinct IDs — the
#                     "trees flickering on every frame" closing-hero
#                     of the M10 blog draft and the visual motivation
#                     for the entire Phase 3 plan.
#
#   2. m4_baseline  — M10 blog's published baseline (post-tuning).
#                     CV filter, min_hits=3, process_noise=0.5,
#                     max_misses=10. Result: 979 distinct IDs.
#
#   3. m13          — IMM + appearance (λ=0.2) without cascade.
#                     The M13 best-config that hit ≤250 by raising
#                     max_misses=300. Result: 237 distinct IDs.
#
#   4. m13_5        — IMM + cascade matching (max_age=300). The
#                     Phase-3.5 production stack. Result: 99 distinct.
#
# Usage:
#   bash scripts/render_blog_animations.sh m4_pretune
#   bash scripts/render_blog_animations.sh m4_baseline
#   bash scripts/render_blog_animations.sh m13
#   bash scripts/render_blog_animations.sh m13_5
#   bash scripts/render_blog_animations.sh all
#
# Outputs (per config):
#   results_m4/blog_renders/<config>/tracks.csv
#   results_m4/blog_renders/<config>/sort_vs_dbscan.mp4
#   results_m4/blog_renders/<config>/sort_vs_dbscan.gif
#   results_m4/blog_renders/<config>/metrics.json
#
# Wall-clock: each config takes ~30 sec for the runner stage and
# ~10 minutes for the matplotlib animation render. Run individually
# or `all` (~30 min total).

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${REPO_ROOT}"

CONFIG="${1:-}"
if [[ -z "${CONFIG}" ]]; then
    cat <<USAGE
Usage: $0 <config>
  config in: m4_baseline | m13 | m13_5 | all
USAGE
    exit 1
fi

# -----------------------------------------------------------------------------
# Inputs (shared across all configs)
# -----------------------------------------------------------------------------
EXT_ROOT="${TP_M4_EXT_ROOT:-/media/nishant/SeeGayt2/terra_perceive/m4_perframe}"
CLUSTERS_DIR="${EXT_ROOT}/clusters_sweetspot"
LIDAR_DIR="data/extracted_frames_full"
CAM_DIR="${EXT_ROOT}/extracted_frames_camera"

DET_CSV="results_m4/ablation_g/rellis_detections.csv"
FEAT_CSV="results_m4/ablation_g/rellis_detections.features.csv"

OUT_BASE="results_m4/blog_renders"
RUNNER="./build/construction_perception/tracker_runner"
PYTHON="${PYTHON:-python3}"

# Sanity: detections + features CSVs must exist (regenerated by
# run_tracker_on_rellis.sh once with --use-appearance).
if [[ ! -f "${DET_CSV}" ]]; then
    echo "ERROR: ${DET_CSV} missing — run scripts/run_tracker_on_rellis.sh first"
    exit 1
fi
if [[ ! -f "${FEAT_CSV}" ]]; then
    echo "ERROR: ${FEAT_CSV} missing — run with TP_M4_USE_APPEARANCE=1 first"
    exit 1
fi

# Determine the frame range from the detections CSV.
LAST_FRAME=$(awk -F, 'NR>1 {print $1}' "${DET_CSV}" | sort -un | tail -1)
echo "[render-blog] using frames 0..${LAST_FRAME}"

# -----------------------------------------------------------------------------
# Per-config dispatch
# -----------------------------------------------------------------------------

run_config() {
    local cfg="$1"
    local out_dir="${OUT_BASE}/${cfg}"
    mkdir -p "${out_dir}"
    rm -f "${out_dir}/tracks.csv" "${out_dir}/metrics.json"

    case "${cfg}" in
        m4_pretune)
            echo "============================================================"
            echo "[render-blog] CONFIG: m4_pretune (CV, min_hits=1, p_n=2.0, max_misses=10)"
            echo "                       — the original 1678-track flickering baseline"
            echo "============================================================"
            "${RUNNER}" \
                --detections     "${DET_CSV}" \
                --solver         munkres \
                --filter         cv \
                --max-dist       5.0 \
                --max-misses     10 \
                --max-age        0 \
                --min-hits       1 \
                --dt             0.1 \
                --process-noise  2.0 \
                --meas-noise     0.3 \
                --snapshot-every 0 \
                --out            "${out_dir}" \
                --verbose
            ;;
        m4_baseline)
            echo "============================================================"
            echo "[render-blog] CONFIG: m4_baseline (CV, max_misses=10, no appearance, no cascade)"
            echo "============================================================"
            "${RUNNER}" \
                --detections     "${DET_CSV}" \
                --solver         munkres \
                --filter         cv \
                --max-dist       5.0 \
                --max-misses     10 \
                --max-age        0 \
                --min-hits       3 \
                --dt             0.1 \
                --process-noise  0.5 \
                --meas-noise     0.3 \
                --snapshot-every 0 \
                --out            "${out_dir}" \
                --verbose
            ;;
        m13)
            echo "============================================================"
            echo "[render-blog] CONFIG: m13 (IMM + appearance λ=0.2, max_misses=300, no cascade)"
            echo "============================================================"
            "${RUNNER}" \
                --detections     "${DET_CSV}" \
                --features-csv   "${FEAT_CSV}" \
                --use-appearance --appearance-weight 0.2 --embedding-alpha 0.1 \
                --solver         munkres \
                --filter         imm \
                --max-dist       5.0 \
                --max-misses     300 \
                --max-age        0 \
                --min-hits       3 \
                --dt             0.1 \
                --process-noise  0.5 \
                --meas-noise     0.3 \
                --snapshot-every 0 \
                --out            "${out_dir}" \
                --verbose
            ;;
        m13_5)
            echo "============================================================"
            echo "[render-blog] CONFIG: m13_5 (IMM + cascade matching, max_age=300, no appearance)"
            echo "============================================================"
            "${RUNNER}" \
                --detections     "${DET_CSV}" \
                --solver         munkres \
                --filter         imm \
                --max-dist       5.0 \
                --max-misses     10 \
                --max-age        300 \
                --min-hits       3 \
                --dt             0.1 \
                --process-noise  0.5 \
                --meas-noise     0.3 \
                --snapshot-every 0 \
                --out            "${out_dir}" \
                --verbose
            ;;
        *)
            echo "ERROR: unknown config '${cfg}'"
            exit 1
            ;;
    esac

    # Headline summary.
    local n_tracks
    n_tracks=$(awk -F, 'NR>1 {ids[$2]=1} END {print length(ids)}' "${out_dir}/tracks.csv")
    local mean_life
    mean_life=$(awk -F, 'NR>1 {n[$2]++} END {s=0; for (id in n) s+=n[id]; printf "%.2f", s/length(n)}' "${out_dir}/tracks.csv")
    echo "[render-blog] ${cfg}: ${n_tracks} distinct, ${mean_life} mean lifetime"

    # Animation render. Single-process matplotlib — slow.
    echo "[render-blog] rendering 3-panel animation (~10 min single-process)"
    "${PYTHON}" scripts/animate_tracker_vs_dbscan.py \
        --lidar-dir       "${LIDAR_DIR}" \
        --camera-dir      "${CAM_DIR}" \
        --clusters-dir    "${CLUSTERS_DIR}" \
        --tracks-csv      "${out_dir}/tracks.csv" \
        --frame-start     0 \
        --frame-end       "${LAST_FRAME}" \
        --fps             10 \
        --stride          5 \
        --out-mp4         "${out_dir}/sort_vs_dbscan.mp4" \
        --out-gif         "${out_dir}/sort_vs_dbscan.gif"

    echo
    echo "================ blog render summary: ${cfg} ================"
    echo "  Tracks CSV     : ${out_dir}/tracks.csv"
    echo "  Distinct tracks: ${n_tracks}"
    echo "  Mean lifetime  : ${mean_life}"
    echo "  Animation MP4  : ${out_dir}/sort_vs_dbscan.mp4"
    echo "  Animation GIF  : ${out_dir}/sort_vs_dbscan.gif"
    echo "============================================================="
}

case "${CONFIG}" in
    m4_pretune|m4_baseline|m13|m13_5)
        run_config "${CONFIG}"
        ;;
    all)
        for c in m4_pretune m4_baseline m13 m13_5; do
            run_config "${c}"
            echo
        done
        ;;
    *)
        echo "ERROR: unknown config '${CONFIG}' (expected m4_pretune | m4_baseline | m13 | m13_5 | all)"
        exit 1
        ;;
esac

echo
echo "[render-blog] DONE."
